// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feapi/feapi.proto

/*
Package feapi is a generated protocol buffer package.

It is generated from these files:
	feapi/feapi.proto

It has these top-level messages:
	BEReadyRequest
	BEReadyResponse
	SetClientAPIServerPortRequest
	SetClientAPIServerPortResponse
	AllBoardsRequest
	AllBoardsResponse
	ThreadAndPostsRequest
	ThreadAndPostsResponse
	BoardAndThreadsRequest
	BoardAndThreadsResponse
	BoardSignalRequest
	BoardSignalResponse
	UserAndGraphRequest
	UserAndGraphResponse
	Event
	ContentEventPayload
	ContentEventResponse
	SignalEventPayload
	SignalEventResponse
	UncompiledEntityByKeyRequest
	UncompiledEntityByKeyResponse
	InflightsPruneRequest
	InflightsPruneResponse
	BackendAmbientStatusPayload
	BackendAmbientStatusResponse
	AmbientStatusRequest
	AmbientStatusResponse
	HomeViewRequest
	HomeViewResponse
	PopularViewRequest
	PopularViewResponse
	NotificationsRequest
	NotificationsResponse
	NotificationsSignalPayload
	NotificationsSignalResponse
	OnboardCompleteRequest
	OnboardCompleteResponse
	SendAddressPayload
	SendAddressResponse
	FEConfigChangesPayload
	FEConfigChangesResponse
	BoardReportsRequest
	BoardReportsResponse
	SendMintedUsernamesPayload
	SendMintedUsernamesResponse
	ClientVersionPayload
	ClientVersionResponse
	SearchRequestPayload
	SearchRequestResponse
*/
package feapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import feobjects "aether-core/aether/protos/feobjects"
import structprotos "aether-core/aether/protos/mimapi"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	EventType_UNKNOWN_EVENT_TYPE EventType = 0
	EventType_CREATE             EventType = 1
	EventType_UPDATE             EventType = 2
)

var EventType_name = map[int32]string{
	0: "UNKNOWN_EVENT_TYPE",
	1: "CREATE",
	2: "UPDATE",
}
var EventType_value = map[string]int32{
	"UNKNOWN_EVENT_TYPE": 0,
	"CREATE":             1,
	"UPDATE":             2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SignalTargetType int32

const (
	SignalTargetType_UNKNOWN_SIGNAL_TARGET_TYPE SignalTargetType = 0
	SignalTargetType_CONTENT                    SignalTargetType = 1
	SignalTargetType_USER                       SignalTargetType = 2
)

var SignalTargetType_name = map[int32]string{
	0: "UNKNOWN_SIGNAL_TARGET_TYPE",
	1: "CONTENT",
	2: "USER",
}
var SignalTargetType_value = map[string]int32{
	"UNKNOWN_SIGNAL_TARGET_TYPE": 0,
	"CONTENT":                    1,
	"USER":                       2,
}

func (x SignalTargetType) String() string {
	return proto.EnumName(SignalTargetType_name, int32(x))
}
func (SignalTargetType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SignalTypeClass int32

const (
	SignalTypeClass_UNKNOWN_SIGNAL_TYPECLASS SignalTypeClass = 0
	SignalTypeClass_ADDS_TO_DISCUSSION       SignalTypeClass = 1
	SignalTypeClass_FOLLOWS_GUIDELINES       SignalTypeClass = 2
	SignalTypeClass_MOD_ACTIONS              SignalTypeClass = 3
	SignalTypeClass_PUBLIC_TRUST             SignalTypeClass = 4
	SignalTypeClass_NAMING                   SignalTypeClass = 5
	SignalTypeClass_F451                     SignalTypeClass = 6
	SignalTypeClass_PUBLIC_ELECT             SignalTypeClass = 7
)

var SignalTypeClass_name = map[int32]string{
	0: "UNKNOWN_SIGNAL_TYPECLASS",
	1: "ADDS_TO_DISCUSSION",
	2: "FOLLOWS_GUIDELINES",
	3: "MOD_ACTIONS",
	4: "PUBLIC_TRUST",
	5: "NAMING",
	6: "F451",
	7: "PUBLIC_ELECT",
}
var SignalTypeClass_value = map[string]int32{
	"UNKNOWN_SIGNAL_TYPECLASS": 0,
	"ADDS_TO_DISCUSSION":       1,
	"FOLLOWS_GUIDELINES":       2,
	"MOD_ACTIONS":              3,
	"PUBLIC_TRUST":             4,
	"NAMING":                   5,
	"F451":                     6,
	"PUBLIC_ELECT":             7,
}

func (x SignalTypeClass) String() string {
	return proto.EnumName(SignalTypeClass_name, int32(x))
}
func (SignalTypeClass) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SignalType int32

const (
	SignalType_UNKNOWN_SIGNAL_TYPE SignalType = 0
	// ATD: Aggregate
	SignalType_UPVOTE   SignalType = 1
	SignalType_DOWNVOTE SignalType = 2
	// FG
	SignalType_REPORT_TO_MOD SignalType = 3
	// MA
	SignalType_MODBLOCK   SignalType = 4
	SignalType_MODAPPROVE SignalType = 5
	SignalType_MODIGNORE  SignalType = 6
	// PT: Aggregate
	SignalType_FOLLOW SignalType = 7
	SignalType_BLOCK  SignalType = 8
	// Naming
	SignalType_NAME_ASSIGN SignalType = 9
	// F451
	SignalType_CENSOR_ASSIGN SignalType = 10
	// PE: Aggregate
	SignalType_ELECT      SignalType = 11
	SignalType_DISQUALIFY SignalType = 12
	// General
	SignalType_RETRACT SignalType = 13
)

var SignalType_name = map[int32]string{
	0:  "UNKNOWN_SIGNAL_TYPE",
	1:  "UPVOTE",
	2:  "DOWNVOTE",
	3:  "REPORT_TO_MOD",
	4:  "MODBLOCK",
	5:  "MODAPPROVE",
	6:  "MODIGNORE",
	7:  "FOLLOW",
	8:  "BLOCK",
	9:  "NAME_ASSIGN",
	10: "CENSOR_ASSIGN",
	11: "ELECT",
	12: "DISQUALIFY",
	13: "RETRACT",
}
var SignalType_value = map[string]int32{
	"UNKNOWN_SIGNAL_TYPE": 0,
	"UPVOTE":              1,
	"DOWNVOTE":            2,
	"REPORT_TO_MOD":       3,
	"MODBLOCK":            4,
	"MODAPPROVE":          5,
	"MODIGNORE":           6,
	"FOLLOW":              7,
	"BLOCK":               8,
	"NAME_ASSIGN":         9,
	"CENSOR_ASSIGN":       10,
	"ELECT":               11,
	"DISQUALIFY":          12,
	"RETRACT":             13,
}

func (x SignalType) String() string {
	return proto.EnumName(SignalType_name, int32(x))
}
func (SignalType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type UncompiledEntityType int32

const (
	UncompiledEntityType_UNKNOWN_ENTITY_TYPE UncompiledEntityType = 0
	UncompiledEntityType_BOARD               UncompiledEntityType = 1
	UncompiledEntityType_THREAD              UncompiledEntityType = 2
	UncompiledEntityType_POST                UncompiledEntityType = 3
	UncompiledEntityType_VOTE                UncompiledEntityType = 4
	UncompiledEntityType_KEY                 UncompiledEntityType = 5
	UncompiledEntityType_TRUSTSTATE          UncompiledEntityType = 6
)

var UncompiledEntityType_name = map[int32]string{
	0: "UNKNOWN_ENTITY_TYPE",
	1: "BOARD",
	2: "THREAD",
	3: "POST",
	4: "VOTE",
	5: "KEY",
	6: "TRUSTSTATE",
}
var UncompiledEntityType_value = map[string]int32{
	"UNKNOWN_ENTITY_TYPE": 0,
	"BOARD":               1,
	"THREAD":              2,
	"POST":                3,
	"VOTE":                4,
	"KEY":                 5,
	"TRUSTSTATE":          6,
}

func (x UncompiledEntityType) String() string {
	return proto.EnumName(UncompiledEntityType_name, int32(x))
}
func (UncompiledEntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type BEReadyRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Port    int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *BEReadyRequest) Reset()                    { *m = BEReadyRequest{} }
func (m *BEReadyRequest) String() string            { return proto.CompactTextString(m) }
func (*BEReadyRequest) ProtoMessage()               {}
func (*BEReadyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BEReadyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BEReadyRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type BEReadyResponse struct {
}

func (m *BEReadyResponse) Reset()                    { *m = BEReadyResponse{} }
func (m *BEReadyResponse) String() string            { return proto.CompactTextString(m) }
func (*BEReadyResponse) ProtoMessage()               {}
func (*BEReadyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SetClientAPIServerPortRequest struct {
	Port int32 `protobuf:"varint,1,opt,name=Port" json:"Port,omitempty"`
}

func (m *SetClientAPIServerPortRequest) Reset()                    { *m = SetClientAPIServerPortRequest{} }
func (m *SetClientAPIServerPortRequest) String() string            { return proto.CompactTextString(m) }
func (*SetClientAPIServerPortRequest) ProtoMessage()               {}
func (*SetClientAPIServerPortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetClientAPIServerPortRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type SetClientAPIServerPortResponse struct {
}

func (m *SetClientAPIServerPortResponse) Reset()                    { *m = SetClientAPIServerPortResponse{} }
func (m *SetClientAPIServerPortResponse) String() string            { return proto.CompactTextString(m) }
func (*SetClientAPIServerPortResponse) ProtoMessage()               {}
func (*SetClientAPIServerPortResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type AllBoardsRequest struct {
}

func (m *AllBoardsRequest) Reset()                    { *m = AllBoardsRequest{} }
func (m *AllBoardsRequest) String() string            { return proto.CompactTextString(m) }
func (*AllBoardsRequest) ProtoMessage()               {}
func (*AllBoardsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type AllBoardsResponse struct {
	AllBoards []*feobjects.CompiledBoardEntity `protobuf:"bytes,1,rep,name=AllBoards" json:"AllBoards,omitempty"`
}

func (m *AllBoardsResponse) Reset()                    { *m = AllBoardsResponse{} }
func (m *AllBoardsResponse) String() string            { return proto.CompactTextString(m) }
func (*AllBoardsResponse) ProtoMessage()               {}
func (*AllBoardsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AllBoardsResponse) GetAllBoards() []*feobjects.CompiledBoardEntity {
	if m != nil {
		return m.AllBoards
	}
	return nil
}

type ThreadAndPostsRequest struct {
	BoardFingerprint  string `protobuf:"bytes,1,opt,name=BoardFingerprint" json:"BoardFingerprint,omitempty"`
	ThreadFingerprint string `protobuf:"bytes,2,opt,name=ThreadFingerprint" json:"ThreadFingerprint,omitempty"`
}

func (m *ThreadAndPostsRequest) Reset()                    { *m = ThreadAndPostsRequest{} }
func (m *ThreadAndPostsRequest) String() string            { return proto.CompactTextString(m) }
func (*ThreadAndPostsRequest) ProtoMessage()               {}
func (*ThreadAndPostsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ThreadAndPostsRequest) GetBoardFingerprint() string {
	if m != nil {
		return m.BoardFingerprint
	}
	return ""
}

func (m *ThreadAndPostsRequest) GetThreadFingerprint() string {
	if m != nil {
		return m.ThreadFingerprint
	}
	return ""
}

type ThreadAndPostsResponse struct {
	Board  *feobjects.CompiledBoardEntity  `protobuf:"bytes,1,opt,name=Board" json:"Board,omitempty"`
	Thread *feobjects.CompiledThreadEntity `protobuf:"bytes,2,opt,name=Thread" json:"Thread,omitempty"`
	Posts  []*feobjects.CompiledPostEntity `protobuf:"bytes,3,rep,name=Posts" json:"Posts,omitempty"`
}

func (m *ThreadAndPostsResponse) Reset()                    { *m = ThreadAndPostsResponse{} }
func (m *ThreadAndPostsResponse) String() string            { return proto.CompactTextString(m) }
func (*ThreadAndPostsResponse) ProtoMessage()               {}
func (*ThreadAndPostsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ThreadAndPostsResponse) GetBoard() *feobjects.CompiledBoardEntity {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *ThreadAndPostsResponse) GetThread() *feobjects.CompiledThreadEntity {
	if m != nil {
		return m.Thread
	}
	return nil
}

func (m *ThreadAndPostsResponse) GetPosts() []*feobjects.CompiledPostEntity {
	if m != nil {
		return m.Posts
	}
	return nil
}

type BoardAndThreadsRequest struct {
	BoardFingerprint string `protobuf:"bytes,1,opt,name=BoardFingerprint" json:"BoardFingerprint,omitempty"`
	SortThreadsByNew bool   `protobuf:"varint,2,opt,name=SortThreadsByNew" json:"SortThreadsByNew,omitempty"`
}

func (m *BoardAndThreadsRequest) Reset()                    { *m = BoardAndThreadsRequest{} }
func (m *BoardAndThreadsRequest) String() string            { return proto.CompactTextString(m) }
func (*BoardAndThreadsRequest) ProtoMessage()               {}
func (*BoardAndThreadsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BoardAndThreadsRequest) GetBoardFingerprint() string {
	if m != nil {
		return m.BoardFingerprint
	}
	return ""
}

func (m *BoardAndThreadsRequest) GetSortThreadsByNew() bool {
	if m != nil {
		return m.SortThreadsByNew
	}
	return false
}

type BoardAndThreadsResponse struct {
	Board   *feobjects.CompiledBoardEntity    `protobuf:"bytes,1,opt,name=Board" json:"Board,omitempty"`
	Threads []*feobjects.CompiledThreadEntity `protobuf:"bytes,2,rep,name=Threads" json:"Threads,omitempty"`
}

func (m *BoardAndThreadsResponse) Reset()                    { *m = BoardAndThreadsResponse{} }
func (m *BoardAndThreadsResponse) String() string            { return proto.CompactTextString(m) }
func (*BoardAndThreadsResponse) ProtoMessage()               {}
func (*BoardAndThreadsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BoardAndThreadsResponse) GetBoard() *feobjects.CompiledBoardEntity {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *BoardAndThreadsResponse) GetThreads() []*feobjects.CompiledThreadEntity {
	if m != nil {
		return m.Threads
	}
	return nil
}

type BoardSignalRequest struct {
	Fingerprint  string `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Subscribed   bool   `protobuf:"varint,2,opt,name=Subscribed" json:"Subscribed,omitempty"`
	Notify       bool   `protobuf:"varint,3,opt,name=Notify" json:"Notify,omitempty"`
	LastSeen     int64  `protobuf:"varint,4,opt,name=LastSeen" json:"LastSeen,omitempty"`
	LastSeenOnly bool   `protobuf:"varint,5,opt,name=LastSeenOnly" json:"LastSeenOnly,omitempty"`
}

func (m *BoardSignalRequest) Reset()                    { *m = BoardSignalRequest{} }
func (m *BoardSignalRequest) String() string            { return proto.CompactTextString(m) }
func (*BoardSignalRequest) ProtoMessage()               {}
func (*BoardSignalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BoardSignalRequest) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *BoardSignalRequest) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

func (m *BoardSignalRequest) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func (m *BoardSignalRequest) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *BoardSignalRequest) GetLastSeenOnly() bool {
	if m != nil {
		return m.LastSeenOnly
	}
	return false
}

type BoardSignalResponse struct {
	Committed bool `protobuf:"varint,1,opt,name=Committed" json:"Committed,omitempty"`
}

func (m *BoardSignalResponse) Reset()                    { *m = BoardSignalResponse{} }
func (m *BoardSignalResponse) String() string            { return proto.CompactTextString(m) }
func (*BoardSignalResponse) ProtoMessage()               {}
func (*BoardSignalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BoardSignalResponse) GetCommitted() bool {
	if m != nil {
		return m.Committed
	}
	return false
}

type UserAndGraphRequest struct {
	Fingerprint          string `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	UserEntityRequested  bool   `protobuf:"varint,2,opt,name=UserEntityRequested" json:"UserEntityRequested,omitempty"`
	UserBoardsRequested  bool   `protobuf:"varint,6,opt,name=UserBoardsRequested" json:"UserBoardsRequested,omitempty"`
	UserThreadsRequested bool   `protobuf:"varint,4,opt,name=UserThreadsRequested" json:"UserThreadsRequested,omitempty"`
	UserPostsRequested   bool   `protobuf:"varint,5,opt,name=UserPostsRequested" json:"UserPostsRequested,omitempty"`
}

func (m *UserAndGraphRequest) Reset()                    { *m = UserAndGraphRequest{} }
func (m *UserAndGraphRequest) String() string            { return proto.CompactTextString(m) }
func (*UserAndGraphRequest) ProtoMessage()               {}
func (*UserAndGraphRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *UserAndGraphRequest) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *UserAndGraphRequest) GetUserEntityRequested() bool {
	if m != nil {
		return m.UserEntityRequested
	}
	return false
}

func (m *UserAndGraphRequest) GetUserBoardsRequested() bool {
	if m != nil {
		return m.UserBoardsRequested
	}
	return false
}

func (m *UserAndGraphRequest) GetUserThreadsRequested() bool {
	if m != nil {
		return m.UserThreadsRequested
	}
	return false
}

func (m *UserAndGraphRequest) GetUserPostsRequested() bool {
	if m != nil {
		return m.UserPostsRequested
	}
	return false
}

type UserAndGraphResponse struct {
	User                 *feobjects.CompiledUserEntity     `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Boards               []*feobjects.CompiledBoardEntity  `protobuf:"bytes,2,rep,name=Boards" json:"Boards,omitempty"`
	Threads              []*feobjects.CompiledThreadEntity `protobuf:"bytes,3,rep,name=Threads" json:"Threads,omitempty"`
	Posts                []*feobjects.CompiledPostEntity   `protobuf:"bytes,4,rep,name=Posts" json:"Posts,omitempty"`
	UserEntityRequested  bool                              `protobuf:"varint,5,opt,name=UserEntityRequested" json:"UserEntityRequested,omitempty"`
	UserBoardsRequested  bool                              `protobuf:"varint,6,opt,name=UserBoardsRequested" json:"UserBoardsRequested,omitempty"`
	UserThreadsRequested bool                              `protobuf:"varint,7,opt,name=UserThreadsRequested" json:"UserThreadsRequested,omitempty"`
	UserPostsRequested   bool                              `protobuf:"varint,8,opt,name=UserPostsRequested" json:"UserPostsRequested,omitempty"`
}

func (m *UserAndGraphResponse) Reset()                    { *m = UserAndGraphResponse{} }
func (m *UserAndGraphResponse) String() string            { return proto.CompactTextString(m) }
func (*UserAndGraphResponse) ProtoMessage()               {}
func (*UserAndGraphResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UserAndGraphResponse) GetUser() *feobjects.CompiledUserEntity {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserAndGraphResponse) GetBoards() []*feobjects.CompiledBoardEntity {
	if m != nil {
		return m.Boards
	}
	return nil
}

func (m *UserAndGraphResponse) GetThreads() []*feobjects.CompiledThreadEntity {
	if m != nil {
		return m.Threads
	}
	return nil
}

func (m *UserAndGraphResponse) GetPosts() []*feobjects.CompiledPostEntity {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *UserAndGraphResponse) GetUserEntityRequested() bool {
	if m != nil {
		return m.UserEntityRequested
	}
	return false
}

func (m *UserAndGraphResponse) GetUserBoardsRequested() bool {
	if m != nil {
		return m.UserBoardsRequested
	}
	return false
}

func (m *UserAndGraphResponse) GetUserThreadsRequested() bool {
	if m != nil {
		return m.UserThreadsRequested
	}
	return false
}

func (m *UserAndGraphResponse) GetUserPostsRequested() bool {
	if m != nil {
		return m.UserPostsRequested
	}
	return false
}

type Event struct {
	OwnerFingerprint string    `protobuf:"bytes,1,opt,name=OwnerFingerprint" json:"OwnerFingerprint,omitempty"`
	PriorFingerprint string    `protobuf:"bytes,2,opt,name=PriorFingerprint" json:"PriorFingerprint,omitempty"`
	EventType        EventType `protobuf:"varint,3,opt,name=EventType,enum=feapi.EventType" json:"EventType,omitempty"`
	Timestamp        int64     `protobuf:"varint,4,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Event) GetOwnerFingerprint() string {
	if m != nil {
		return m.OwnerFingerprint
	}
	return ""
}

func (m *Event) GetPriorFingerprint() string {
	if m != nil {
		return m.PriorFingerprint
	}
	return ""
}

func (m *Event) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_UNKNOWN_EVENT_TYPE
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ContentEventPayload struct {
	Event      *Event               `protobuf:"bytes,1,opt,name=Event" json:"Event,omitempty"`
	BoardData  *structprotos.Board  `protobuf:"bytes,2,opt,name=BoardData" json:"BoardData,omitempty"`
	ThreadData *structprotos.Thread `protobuf:"bytes,3,opt,name=ThreadData" json:"ThreadData,omitempty"`
	PostData   *structprotos.Post   `protobuf:"bytes,4,opt,name=PostData" json:"PostData,omitempty"`
	KeyData    *structprotos.Key    `protobuf:"bytes,5,opt,name=KeyData" json:"KeyData,omitempty"`
}

func (m *ContentEventPayload) Reset()                    { *m = ContentEventPayload{} }
func (m *ContentEventPayload) String() string            { return proto.CompactTextString(m) }
func (*ContentEventPayload) ProtoMessage()               {}
func (*ContentEventPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ContentEventPayload) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ContentEventPayload) GetBoardData() *structprotos.Board {
	if m != nil {
		return m.BoardData
	}
	return nil
}

func (m *ContentEventPayload) GetThreadData() *structprotos.Thread {
	if m != nil {
		return m.ThreadData
	}
	return nil
}

func (m *ContentEventPayload) GetPostData() *structprotos.Post {
	if m != nil {
		return m.PostData
	}
	return nil
}

func (m *ContentEventPayload) GetKeyData() *structprotos.Key {
	if m != nil {
		return m.KeyData
	}
	return nil
}

type ContentEventResponse struct {
}

func (m *ContentEventResponse) Reset()                    { *m = ContentEventResponse{} }
func (m *ContentEventResponse) String() string            { return proto.CompactTextString(m) }
func (*ContentEventResponse) ProtoMessage()               {}
func (*ContentEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type SignalEventPayload struct {
	Event            *Event           `protobuf:"bytes,1,opt,name=Event" json:"Event,omitempty"`
	SignalTargetType SignalTargetType `protobuf:"varint,2,opt,name=SignalTargetType,enum=feapi.SignalTargetType" json:"SignalTargetType,omitempty"`
	// ----------  Defined for targettype=content  ----------
	TargetBoard  string `protobuf:"bytes,3,opt,name=TargetBoard" json:"TargetBoard,omitempty"`
	TargetThread string `protobuf:"bytes,4,opt,name=TargetThread" json:"TargetThread,omitempty"`
	// ----------  Defined for targettype=user  ----------
	TargetDomain      string          `protobuf:"bytes,5,opt,name=TargetDomain" json:"TargetDomain,omitempty"`
	TargetExpiry      int64           `protobuf:"varint,6,opt,name=TargetExpiry" json:"TargetExpiry,omitempty"`
	Meta              string          `protobuf:"bytes,7,opt,name=Meta" json:"Meta,omitempty"`
	TargetFingerprint string          `protobuf:"bytes,8,opt,name=TargetFingerprint" json:"TargetFingerprint,omitempty"`
	SignalTypeClass   SignalTypeClass `protobuf:"varint,9,opt,name=SignalTypeClass,enum=feapi.SignalTypeClass" json:"SignalTypeClass,omitempty"`
	SignalType        SignalType      `protobuf:"varint,10,opt,name=SignalType,enum=feapi.SignalType" json:"SignalType,omitempty"`
	SignalText        string          `protobuf:"bytes,11,opt,name=SignalText" json:"SignalText,omitempty"`
}

func (m *SignalEventPayload) Reset()                    { *m = SignalEventPayload{} }
func (m *SignalEventPayload) String() string            { return proto.CompactTextString(m) }
func (*SignalEventPayload) ProtoMessage()               {}
func (*SignalEventPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SignalEventPayload) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *SignalEventPayload) GetSignalTargetType() SignalTargetType {
	if m != nil {
		return m.SignalTargetType
	}
	return SignalTargetType_UNKNOWN_SIGNAL_TARGET_TYPE
}

func (m *SignalEventPayload) GetTargetBoard() string {
	if m != nil {
		return m.TargetBoard
	}
	return ""
}

func (m *SignalEventPayload) GetTargetThread() string {
	if m != nil {
		return m.TargetThread
	}
	return ""
}

func (m *SignalEventPayload) GetTargetDomain() string {
	if m != nil {
		return m.TargetDomain
	}
	return ""
}

func (m *SignalEventPayload) GetTargetExpiry() int64 {
	if m != nil {
		return m.TargetExpiry
	}
	return 0
}

func (m *SignalEventPayload) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *SignalEventPayload) GetTargetFingerprint() string {
	if m != nil {
		return m.TargetFingerprint
	}
	return ""
}

func (m *SignalEventPayload) GetSignalTypeClass() SignalTypeClass {
	if m != nil {
		return m.SignalTypeClass
	}
	return SignalTypeClass_UNKNOWN_SIGNAL_TYPECLASS
}

func (m *SignalEventPayload) GetSignalType() SignalType {
	if m != nil {
		return m.SignalType
	}
	return SignalType_UNKNOWN_SIGNAL_TYPE
}

func (m *SignalEventPayload) GetSignalText() string {
	if m != nil {
		return m.SignalText
	}
	return ""
}

type SignalEventResponse struct {
}

func (m *SignalEventResponse) Reset()                    { *m = SignalEventResponse{} }
func (m *SignalEventResponse) String() string            { return proto.CompactTextString(m) }
func (*SignalEventResponse) ProtoMessage()               {}
func (*SignalEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type UncompiledEntityByKeyRequest struct {
	EntityType       UncompiledEntityType `protobuf:"varint,1,opt,name=EntityType,enum=feapi.UncompiledEntityType" json:"EntityType,omitempty"`
	Limit            int32                `protobuf:"varint,2,opt,name=Limit" json:"Limit,omitempty"`
	Offset           int32                `protobuf:"varint,3,opt,name=Offset" json:"Offset,omitempty"`
	OwnerFingerprint string               `protobuf:"bytes,4,opt,name=OwnerFingerprint" json:"OwnerFingerprint,omitempty"`
}

func (m *UncompiledEntityByKeyRequest) Reset()                    { *m = UncompiledEntityByKeyRequest{} }
func (m *UncompiledEntityByKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*UncompiledEntityByKeyRequest) ProtoMessage()               {}
func (*UncompiledEntityByKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *UncompiledEntityByKeyRequest) GetEntityType() UncompiledEntityType {
	if m != nil {
		return m.EntityType
	}
	return UncompiledEntityType_UNKNOWN_ENTITY_TYPE
}

func (m *UncompiledEntityByKeyRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UncompiledEntityByKeyRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *UncompiledEntityByKeyRequest) GetOwnerFingerprint() string {
	if m != nil {
		return m.OwnerFingerprint
	}
	return ""
}

type UncompiledEntityByKeyResponse struct {
	EntityType  UncompiledEntityType       `protobuf:"varint,1,opt,name=EntityType,enum=feapi.UncompiledEntityType" json:"EntityType,omitempty"`
	Boards      []*structprotos.Board      `protobuf:"bytes,2,rep,name=Boards" json:"Boards,omitempty"`
	Threads     []*structprotos.Thread     `protobuf:"bytes,3,rep,name=Threads" json:"Threads,omitempty"`
	Posts       []*structprotos.Post       `protobuf:"bytes,4,rep,name=Posts" json:"Posts,omitempty"`
	Votes       []*structprotos.Vote       `protobuf:"bytes,5,rep,name=Votes" json:"Votes,omitempty"`
	Keys        []*structprotos.Key        `protobuf:"bytes,6,rep,name=Keys" json:"Keys,omitempty"`
	Truststates []*structprotos.Truststate `protobuf:"bytes,7,rep,name=Truststates" json:"Truststates,omitempty"`
}

func (m *UncompiledEntityByKeyResponse) Reset()                    { *m = UncompiledEntityByKeyResponse{} }
func (m *UncompiledEntityByKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*UncompiledEntityByKeyResponse) ProtoMessage()               {}
func (*UncompiledEntityByKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *UncompiledEntityByKeyResponse) GetEntityType() UncompiledEntityType {
	if m != nil {
		return m.EntityType
	}
	return UncompiledEntityType_UNKNOWN_ENTITY_TYPE
}

func (m *UncompiledEntityByKeyResponse) GetBoards() []*structprotos.Board {
	if m != nil {
		return m.Boards
	}
	return nil
}

func (m *UncompiledEntityByKeyResponse) GetThreads() []*structprotos.Thread {
	if m != nil {
		return m.Threads
	}
	return nil
}

func (m *UncompiledEntityByKeyResponse) GetPosts() []*structprotos.Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *UncompiledEntityByKeyResponse) GetVotes() []*structprotos.Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *UncompiledEntityByKeyResponse) GetKeys() []*structprotos.Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *UncompiledEntityByKeyResponse) GetTruststates() []*structprotos.Truststate {
	if m != nil {
		return m.Truststates
	}
	return nil
}

type InflightsPruneRequest struct {
}

func (m *InflightsPruneRequest) Reset()                    { *m = InflightsPruneRequest{} }
func (m *InflightsPruneRequest) String() string            { return proto.CompactTextString(m) }
func (*InflightsPruneRequest) ProtoMessage()               {}
func (*InflightsPruneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type InflightsPruneResponse struct {
}

func (m *InflightsPruneResponse) Reset()                    { *m = InflightsPruneResponse{} }
func (m *InflightsPruneResponse) String() string            { return proto.CompactTextString(m) }
func (*InflightsPruneResponse) ProtoMessage()               {}
func (*InflightsPruneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type BackendAmbientStatusPayload struct {
	BackendAmbientStatus *feobjects.BackendAmbientStatus `protobuf:"bytes,1,opt,name=BackendAmbientStatus" json:"BackendAmbientStatus,omitempty"`
}

func (m *BackendAmbientStatusPayload) Reset()                    { *m = BackendAmbientStatusPayload{} }
func (m *BackendAmbientStatusPayload) String() string            { return proto.CompactTextString(m) }
func (*BackendAmbientStatusPayload) ProtoMessage()               {}
func (*BackendAmbientStatusPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *BackendAmbientStatusPayload) GetBackendAmbientStatus() *feobjects.BackendAmbientStatus {
	if m != nil {
		return m.BackendAmbientStatus
	}
	return nil
}

type BackendAmbientStatusResponse struct {
}

func (m *BackendAmbientStatusResponse) Reset()                    { *m = BackendAmbientStatusResponse{} }
func (m *BackendAmbientStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*BackendAmbientStatusResponse) ProtoMessage()               {}
func (*BackendAmbientStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

//
// These are useful because they allow the client to ask for ambient status in the case it refreshes. This is useful for the status entity.
type AmbientStatusRequest struct {
}

func (m *AmbientStatusRequest) Reset()                    { *m = AmbientStatusRequest{} }
func (m *AmbientStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*AmbientStatusRequest) ProtoMessage()               {}
func (*AmbientStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type AmbientStatusResponse struct {
}

func (m *AmbientStatusResponse) Reset()                    { *m = AmbientStatusResponse{} }
func (m *AmbientStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*AmbientStatusResponse) ProtoMessage()               {}
func (*AmbientStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type HomeViewRequest struct {
}

func (m *HomeViewRequest) Reset()                    { *m = HomeViewRequest{} }
func (m *HomeViewRequest) String() string            { return proto.CompactTextString(m) }
func (*HomeViewRequest) ProtoMessage()               {}
func (*HomeViewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

type HomeViewResponse struct {
}

func (m *HomeViewResponse) Reset()                    { *m = HomeViewResponse{} }
func (m *HomeViewResponse) String() string            { return proto.CompactTextString(m) }
func (*HomeViewResponse) ProtoMessage()               {}
func (*HomeViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type PopularViewRequest struct {
}

func (m *PopularViewRequest) Reset()                    { *m = PopularViewRequest{} }
func (m *PopularViewRequest) String() string            { return proto.CompactTextString(m) }
func (*PopularViewRequest) ProtoMessage()               {}
func (*PopularViewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type PopularViewResponse struct {
}

func (m *PopularViewResponse) Reset()                    { *m = PopularViewResponse{} }
func (m *PopularViewResponse) String() string            { return proto.CompactTextString(m) }
func (*PopularViewResponse) ProtoMessage()               {}
func (*PopularViewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type NotificationsRequest struct {
}

func (m *NotificationsRequest) Reset()                    { *m = NotificationsRequest{} }
func (m *NotificationsRequest) String() string            { return proto.CompactTextString(m) }
func (*NotificationsRequest) ProtoMessage()               {}
func (*NotificationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type NotificationsResponse struct {
}

func (m *NotificationsResponse) Reset()                    { *m = NotificationsResponse{} }
func (m *NotificationsResponse) String() string            { return proto.CompactTextString(m) }
func (*NotificationsResponse) ProtoMessage()               {}
func (*NotificationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type NotificationsSignalPayload struct {
	Seen                bool   `protobuf:"varint,1,opt,name=Seen" json:"Seen,omitempty"`
	ReadItemFingerprint string `protobuf:"bytes,2,opt,name=ReadItemFingerprint" json:"ReadItemFingerprint,omitempty"`
}

func (m *NotificationsSignalPayload) Reset()                    { *m = NotificationsSignalPayload{} }
func (m *NotificationsSignalPayload) String() string            { return proto.CompactTextString(m) }
func (*NotificationsSignalPayload) ProtoMessage()               {}
func (*NotificationsSignalPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *NotificationsSignalPayload) GetSeen() bool {
	if m != nil {
		return m.Seen
	}
	return false
}

func (m *NotificationsSignalPayload) GetReadItemFingerprint() string {
	if m != nil {
		return m.ReadItemFingerprint
	}
	return ""
}

type NotificationsSignalResponse struct {
}

func (m *NotificationsSignalResponse) Reset()                    { *m = NotificationsSignalResponse{} }
func (m *NotificationsSignalResponse) String() string            { return proto.CompactTextString(m) }
func (*NotificationsSignalResponse) ProtoMessage()               {}
func (*NotificationsSignalResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type OnboardCompleteRequest struct {
	OnboardComplete bool `protobuf:"varint,1,opt,name=OnboardComplete" json:"OnboardComplete,omitempty"`
}

func (m *OnboardCompleteRequest) Reset()                    { *m = OnboardCompleteRequest{} }
func (m *OnboardCompleteRequest) String() string            { return proto.CompactTextString(m) }
func (*OnboardCompleteRequest) ProtoMessage()               {}
func (*OnboardCompleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *OnboardCompleteRequest) GetOnboardComplete() bool {
	if m != nil {
		return m.OnboardComplete
	}
	return false
}

type OnboardCompleteResponse struct {
}

func (m *OnboardCompleteResponse) Reset()                    { *m = OnboardCompleteResponse{} }
func (m *OnboardCompleteResponse) String() string            { return proto.CompactTextString(m) }
func (*OnboardCompleteResponse) ProtoMessage()               {}
func (*OnboardCompleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type SendAddressPayload struct {
	Address *structprotos.Address `protobuf:"bytes,1,opt,name=Address" json:"Address,omitempty"`
}

func (m *SendAddressPayload) Reset()                    { *m = SendAddressPayload{} }
func (m *SendAddressPayload) String() string            { return proto.CompactTextString(m) }
func (*SendAddressPayload) ProtoMessage()               {}
func (*SendAddressPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *SendAddressPayload) GetAddress() *structprotos.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type SendAddressResponse struct {
	StatusCode   int32  `protobuf:"varint,1,opt,name=StatusCode" json:"StatusCode,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=ErrorMessage" json:"ErrorMessage,omitempty"`
}

func (m *SendAddressResponse) Reset()                    { *m = SendAddressResponse{} }
func (m *SendAddressResponse) String() string            { return proto.CompactTextString(m) }
func (*SendAddressResponse) ProtoMessage()               {}
func (*SendAddressResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *SendAddressResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SendAddressResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type FEConfigChangesPayload struct {
	ModModeEnabledIsSet                  bool `protobuf:"varint,1,opt,name=ModModeEnabledIsSet" json:"ModModeEnabledIsSet,omitempty"`
	ModModeEnabled                       bool `protobuf:"varint,2,opt,name=ModModeEnabled" json:"ModModeEnabled,omitempty"`
	ExternalContentAutoloadDisabled      bool `protobuf:"varint,3,opt,name=ExternalContentAutoloadDisabled" json:"ExternalContentAutoloadDisabled,omitempty"`
	ExternalContentAutoloadDisabledIsSet bool `protobuf:"varint,4,opt,name=ExternalContentAutoloadDisabledIsSet" json:"ExternalContentAutoloadDisabledIsSet,omitempty"`
}

func (m *FEConfigChangesPayload) Reset()                    { *m = FEConfigChangesPayload{} }
func (m *FEConfigChangesPayload) String() string            { return proto.CompactTextString(m) }
func (*FEConfigChangesPayload) ProtoMessage()               {}
func (*FEConfigChangesPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *FEConfigChangesPayload) GetModModeEnabledIsSet() bool {
	if m != nil {
		return m.ModModeEnabledIsSet
	}
	return false
}

func (m *FEConfigChangesPayload) GetModModeEnabled() bool {
	if m != nil {
		return m.ModModeEnabled
	}
	return false
}

func (m *FEConfigChangesPayload) GetExternalContentAutoloadDisabled() bool {
	if m != nil {
		return m.ExternalContentAutoloadDisabled
	}
	return false
}

func (m *FEConfigChangesPayload) GetExternalContentAutoloadDisabledIsSet() bool {
	if m != nil {
		return m.ExternalContentAutoloadDisabledIsSet
	}
	return false
}

type FEConfigChangesResponse struct {
}

func (m *FEConfigChangesResponse) Reset()                    { *m = FEConfigChangesResponse{} }
func (m *FEConfigChangesResponse) String() string            { return proto.CompactTextString(m) }
func (*FEConfigChangesResponse) ProtoMessage()               {}
func (*FEConfigChangesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type BoardReportsRequest struct {
	BoardFingerprint string `protobuf:"bytes,1,opt,name=BoardFingerprint" json:"BoardFingerprint,omitempty"`
}

func (m *BoardReportsRequest) Reset()                    { *m = BoardReportsRequest{} }
func (m *BoardReportsRequest) String() string            { return proto.CompactTextString(m) }
func (*BoardReportsRequest) ProtoMessage()               {}
func (*BoardReportsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *BoardReportsRequest) GetBoardFingerprint() string {
	if m != nil {
		return m.BoardFingerprint
	}
	return ""
}

type BoardReportsResponse struct {
	ReportsTabEntries []*feobjects.ReportsTabEntry `protobuf:"bytes,1,rep,name=ReportsTabEntries" json:"ReportsTabEntries,omitempty"`
}

func (m *BoardReportsResponse) Reset()                    { *m = BoardReportsResponse{} }
func (m *BoardReportsResponse) String() string            { return proto.CompactTextString(m) }
func (*BoardReportsResponse) ProtoMessage()               {}
func (*BoardReportsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *BoardReportsResponse) GetReportsTabEntries() []*feobjects.ReportsTabEntry {
	if m != nil {
		return m.ReportsTabEntries
	}
	return nil
}

type SendMintedUsernamesPayload struct {
	MintedUsernamesRawJSON string `protobuf:"bytes,1,opt,name=MintedUsernamesRawJSON" json:"MintedUsernamesRawJSON,omitempty"`
}

func (m *SendMintedUsernamesPayload) Reset()                    { *m = SendMintedUsernamesPayload{} }
func (m *SendMintedUsernamesPayload) String() string            { return proto.CompactTextString(m) }
func (*SendMintedUsernamesPayload) ProtoMessage()               {}
func (*SendMintedUsernamesPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *SendMintedUsernamesPayload) GetMintedUsernamesRawJSON() string {
	if m != nil {
		return m.MintedUsernamesRawJSON
	}
	return ""
}

type SendMintedUsernamesResponse struct {
}

func (m *SendMintedUsernamesResponse) Reset()                    { *m = SendMintedUsernamesResponse{} }
func (m *SendMintedUsernamesResponse) String() string            { return proto.CompactTextString(m) }
func (*SendMintedUsernamesResponse) ProtoMessage()               {}
func (*SendMintedUsernamesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

type ClientVersionPayload struct {
	CurrentClientVersion string `protobuf:"bytes,1,opt,name=CurrentClientVersion" json:"CurrentClientVersion,omitempty"`
}

func (m *ClientVersionPayload) Reset()                    { *m = ClientVersionPayload{} }
func (m *ClientVersionPayload) String() string            { return proto.CompactTextString(m) }
func (*ClientVersionPayload) ProtoMessage()               {}
func (*ClientVersionPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *ClientVersionPayload) GetCurrentClientVersion() string {
	if m != nil {
		return m.CurrentClientVersion
	}
	return ""
}

type ClientVersionResponse struct {
	LastKnownClientVersion string `protobuf:"bytes,1,opt,name=LastKnownClientVersion" json:"LastKnownClientVersion,omitempty"`
}

func (m *ClientVersionResponse) Reset()                    { *m = ClientVersionResponse{} }
func (m *ClientVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*ClientVersionResponse) ProtoMessage()               {}
func (*ClientVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *ClientVersionResponse) GetLastKnownClientVersion() string {
	if m != nil {
		return m.LastKnownClientVersion
	}
	return ""
}

type SearchRequestPayload struct {
	SearchType  string `protobuf:"bytes,1,opt,name=SearchType" json:"SearchType,omitempty"`
	SearchQuery string `protobuf:"bytes,2,opt,name=SearchQuery" json:"SearchQuery,omitempty"`
}

func (m *SearchRequestPayload) Reset()                    { *m = SearchRequestPayload{} }
func (m *SearchRequestPayload) String() string            { return proto.CompactTextString(m) }
func (*SearchRequestPayload) ProtoMessage()               {}
func (*SearchRequestPayload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *SearchRequestPayload) GetSearchType() string {
	if m != nil {
		return m.SearchType
	}
	return ""
}

func (m *SearchRequestPayload) GetSearchQuery() string {
	if m != nil {
		return m.SearchQuery
	}
	return ""
}

// Heads up, this will always be empty. The actual result is going to come via the feapi, as a gRPC call initiated by the FE.
type SearchRequestResponse struct {
}

func (m *SearchRequestResponse) Reset()                    { *m = SearchRequestResponse{} }
func (m *SearchRequestResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchRequestResponse) ProtoMessage()               {}
func (*SearchRequestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func init() {
	proto.RegisterType((*BEReadyRequest)(nil), "feapi.BEReadyRequest")
	proto.RegisterType((*BEReadyResponse)(nil), "feapi.BEReadyResponse")
	proto.RegisterType((*SetClientAPIServerPortRequest)(nil), "feapi.SetClientAPIServerPortRequest")
	proto.RegisterType((*SetClientAPIServerPortResponse)(nil), "feapi.SetClientAPIServerPortResponse")
	proto.RegisterType((*AllBoardsRequest)(nil), "feapi.AllBoardsRequest")
	proto.RegisterType((*AllBoardsResponse)(nil), "feapi.AllBoardsResponse")
	proto.RegisterType((*ThreadAndPostsRequest)(nil), "feapi.ThreadAndPostsRequest")
	proto.RegisterType((*ThreadAndPostsResponse)(nil), "feapi.ThreadAndPostsResponse")
	proto.RegisterType((*BoardAndThreadsRequest)(nil), "feapi.BoardAndThreadsRequest")
	proto.RegisterType((*BoardAndThreadsResponse)(nil), "feapi.BoardAndThreadsResponse")
	proto.RegisterType((*BoardSignalRequest)(nil), "feapi.BoardSignalRequest")
	proto.RegisterType((*BoardSignalResponse)(nil), "feapi.BoardSignalResponse")
	proto.RegisterType((*UserAndGraphRequest)(nil), "feapi.UserAndGraphRequest")
	proto.RegisterType((*UserAndGraphResponse)(nil), "feapi.UserAndGraphResponse")
	proto.RegisterType((*Event)(nil), "feapi.Event")
	proto.RegisterType((*ContentEventPayload)(nil), "feapi.ContentEventPayload")
	proto.RegisterType((*ContentEventResponse)(nil), "feapi.ContentEventResponse")
	proto.RegisterType((*SignalEventPayload)(nil), "feapi.SignalEventPayload")
	proto.RegisterType((*SignalEventResponse)(nil), "feapi.SignalEventResponse")
	proto.RegisterType((*UncompiledEntityByKeyRequest)(nil), "feapi.UncompiledEntityByKeyRequest")
	proto.RegisterType((*UncompiledEntityByKeyResponse)(nil), "feapi.UncompiledEntityByKeyResponse")
	proto.RegisterType((*InflightsPruneRequest)(nil), "feapi.InflightsPruneRequest")
	proto.RegisterType((*InflightsPruneResponse)(nil), "feapi.InflightsPruneResponse")
	proto.RegisterType((*BackendAmbientStatusPayload)(nil), "feapi.BackendAmbientStatusPayload")
	proto.RegisterType((*BackendAmbientStatusResponse)(nil), "feapi.BackendAmbientStatusResponse")
	proto.RegisterType((*AmbientStatusRequest)(nil), "feapi.AmbientStatusRequest")
	proto.RegisterType((*AmbientStatusResponse)(nil), "feapi.AmbientStatusResponse")
	proto.RegisterType((*HomeViewRequest)(nil), "feapi.HomeViewRequest")
	proto.RegisterType((*HomeViewResponse)(nil), "feapi.HomeViewResponse")
	proto.RegisterType((*PopularViewRequest)(nil), "feapi.PopularViewRequest")
	proto.RegisterType((*PopularViewResponse)(nil), "feapi.PopularViewResponse")
	proto.RegisterType((*NotificationsRequest)(nil), "feapi.NotificationsRequest")
	proto.RegisterType((*NotificationsResponse)(nil), "feapi.NotificationsResponse")
	proto.RegisterType((*NotificationsSignalPayload)(nil), "feapi.NotificationsSignalPayload")
	proto.RegisterType((*NotificationsSignalResponse)(nil), "feapi.NotificationsSignalResponse")
	proto.RegisterType((*OnboardCompleteRequest)(nil), "feapi.OnboardCompleteRequest")
	proto.RegisterType((*OnboardCompleteResponse)(nil), "feapi.OnboardCompleteResponse")
	proto.RegisterType((*SendAddressPayload)(nil), "feapi.SendAddressPayload")
	proto.RegisterType((*SendAddressResponse)(nil), "feapi.SendAddressResponse")
	proto.RegisterType((*FEConfigChangesPayload)(nil), "feapi.FEConfigChangesPayload")
	proto.RegisterType((*FEConfigChangesResponse)(nil), "feapi.FEConfigChangesResponse")
	proto.RegisterType((*BoardReportsRequest)(nil), "feapi.BoardReportsRequest")
	proto.RegisterType((*BoardReportsResponse)(nil), "feapi.BoardReportsResponse")
	proto.RegisterType((*SendMintedUsernamesPayload)(nil), "feapi.SendMintedUsernamesPayload")
	proto.RegisterType((*SendMintedUsernamesResponse)(nil), "feapi.SendMintedUsernamesResponse")
	proto.RegisterType((*ClientVersionPayload)(nil), "feapi.ClientVersionPayload")
	proto.RegisterType((*ClientVersionResponse)(nil), "feapi.ClientVersionResponse")
	proto.RegisterType((*SearchRequestPayload)(nil), "feapi.SearchRequestPayload")
	proto.RegisterType((*SearchRequestResponse)(nil), "feapi.SearchRequestResponse")
	proto.RegisterEnum("feapi.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("feapi.SignalTargetType", SignalTargetType_name, SignalTargetType_value)
	proto.RegisterEnum("feapi.SignalTypeClass", SignalTypeClass_name, SignalTypeClass_value)
	proto.RegisterEnum("feapi.SignalType", SignalType_name, SignalType_value)
	proto.RegisterEnum("feapi.UncompiledEntityType", UncompiledEntityType_name, UncompiledEntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FrontendAPI service

type FrontendAPIClient interface {
	// ----------  Methods used by client  ----------
	SetClientAPIServerPort(ctx context.Context, in *SetClientAPIServerPortRequest, opts ...grpc.CallOption) (*SetClientAPIServerPortResponse, error)
	GetThreadAndPosts(ctx context.Context, in *ThreadAndPostsRequest, opts ...grpc.CallOption) (*ThreadAndPostsResponse, error)
	GetBoardAndThreads(ctx context.Context, in *BoardAndThreadsRequest, opts ...grpc.CallOption) (*BoardAndThreadsResponse, error)
	GetAllBoards(ctx context.Context, in *AllBoardsRequest, opts ...grpc.CallOption) (*AllBoardsResponse, error)
	SetBoardSignal(ctx context.Context, in *BoardSignalRequest, opts ...grpc.CallOption) (*BoardSignalResponse, error)
	GetUserAndGraph(ctx context.Context, in *UserAndGraphRequest, opts ...grpc.CallOption) (*UserAndGraphResponse, error)
	SendContentEvent(ctx context.Context, in *ContentEventPayload, opts ...grpc.CallOption) (*ContentEventResponse, error)
	SendSignalEvent(ctx context.Context, in *SignalEventPayload, opts ...grpc.CallOption) (*SignalEventResponse, error)
	GetUncompiledEntityByKey(ctx context.Context, in *UncompiledEntityByKeyRequest, opts ...grpc.CallOption) (*UncompiledEntityByKeyResponse, error)
	SendInflightsPruneRequest(ctx context.Context, in *InflightsPruneRequest, opts ...grpc.CallOption) (*InflightsPruneResponse, error)
	RequestAmbientStatus(ctx context.Context, in *AmbientStatusRequest, opts ...grpc.CallOption) (*AmbientStatusResponse, error)
	// ^ Client requests ambient status to be sent in.
	RequestHomeView(ctx context.Context, in *HomeViewRequest, opts ...grpc.CallOption) (*HomeViewResponse, error)
	RequestPopularView(ctx context.Context, in *PopularViewRequest, opts ...grpc.CallOption) (*PopularViewResponse, error)
	RequestNotifications(ctx context.Context, in *NotificationsRequest, opts ...grpc.CallOption) (*NotificationsResponse, error)
	SetNotificationsSignal(ctx context.Context, in *NotificationsSignalPayload, opts ...grpc.CallOption) (*NotificationsSignalResponse, error)
	// rpc RequestOnboardCompleteStatus(OnboardCompleteStatusRequest) returns (OnboardCompleteStatusResponse) {}
	SetOnboardComplete(ctx context.Context, in *OnboardCompleteRequest, opts ...grpc.CallOption) (*OnboardCompleteResponse, error)
	SendAddress(ctx context.Context, in *SendAddressPayload, opts ...grpc.CallOption) (*SendAddressResponse, error)
	SendFEConfigChanges(ctx context.Context, in *FEConfigChangesPayload, opts ...grpc.CallOption) (*FEConfigChangesResponse, error)
	RequestBoardReports(ctx context.Context, in *BoardReportsRequest, opts ...grpc.CallOption) (*BoardReportsResponse, error)
	SendMintedUsernames(ctx context.Context, in *SendMintedUsernamesPayload, opts ...grpc.CallOption) (*SendMintedUsernamesResponse, error)
	SendClientVersion(ctx context.Context, in *ClientVersionPayload, opts ...grpc.CallOption) (*ClientVersionResponse, error)
	SendSearchRequest(ctx context.Context, in *SearchRequestPayload, opts ...grpc.CallOption) (*SearchRequestResponse, error)
	// ----------  Methods used by backend  ----------
	BackendReady(ctx context.Context, in *BEReadyRequest, opts ...grpc.CallOption) (*BEReadyResponse, error)
	SendBackendAmbientStatus(ctx context.Context, in *BackendAmbientStatusPayload, opts ...grpc.CallOption) (*BackendAmbientStatusResponse, error)
}

type frontendAPIClient struct {
	cc *grpc.ClientConn
}

func NewFrontendAPIClient(cc *grpc.ClientConn) FrontendAPIClient {
	return &frontendAPIClient{cc}
}

func (c *frontendAPIClient) SetClientAPIServerPort(ctx context.Context, in *SetClientAPIServerPortRequest, opts ...grpc.CallOption) (*SetClientAPIServerPortResponse, error) {
	out := new(SetClientAPIServerPortResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SetClientAPIServerPort", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) GetThreadAndPosts(ctx context.Context, in *ThreadAndPostsRequest, opts ...grpc.CallOption) (*ThreadAndPostsResponse, error) {
	out := new(ThreadAndPostsResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/GetThreadAndPosts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) GetBoardAndThreads(ctx context.Context, in *BoardAndThreadsRequest, opts ...grpc.CallOption) (*BoardAndThreadsResponse, error) {
	out := new(BoardAndThreadsResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/GetBoardAndThreads", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) GetAllBoards(ctx context.Context, in *AllBoardsRequest, opts ...grpc.CallOption) (*AllBoardsResponse, error) {
	out := new(AllBoardsResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/GetAllBoards", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SetBoardSignal(ctx context.Context, in *BoardSignalRequest, opts ...grpc.CallOption) (*BoardSignalResponse, error) {
	out := new(BoardSignalResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SetBoardSignal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) GetUserAndGraph(ctx context.Context, in *UserAndGraphRequest, opts ...grpc.CallOption) (*UserAndGraphResponse, error) {
	out := new(UserAndGraphResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/GetUserAndGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendContentEvent(ctx context.Context, in *ContentEventPayload, opts ...grpc.CallOption) (*ContentEventResponse, error) {
	out := new(ContentEventResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendContentEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendSignalEvent(ctx context.Context, in *SignalEventPayload, opts ...grpc.CallOption) (*SignalEventResponse, error) {
	out := new(SignalEventResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendSignalEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) GetUncompiledEntityByKey(ctx context.Context, in *UncompiledEntityByKeyRequest, opts ...grpc.CallOption) (*UncompiledEntityByKeyResponse, error) {
	out := new(UncompiledEntityByKeyResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/GetUncompiledEntityByKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendInflightsPruneRequest(ctx context.Context, in *InflightsPruneRequest, opts ...grpc.CallOption) (*InflightsPruneResponse, error) {
	out := new(InflightsPruneResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendInflightsPruneRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) RequestAmbientStatus(ctx context.Context, in *AmbientStatusRequest, opts ...grpc.CallOption) (*AmbientStatusResponse, error) {
	out := new(AmbientStatusResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/RequestAmbientStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) RequestHomeView(ctx context.Context, in *HomeViewRequest, opts ...grpc.CallOption) (*HomeViewResponse, error) {
	out := new(HomeViewResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/RequestHomeView", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) RequestPopularView(ctx context.Context, in *PopularViewRequest, opts ...grpc.CallOption) (*PopularViewResponse, error) {
	out := new(PopularViewResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/RequestPopularView", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) RequestNotifications(ctx context.Context, in *NotificationsRequest, opts ...grpc.CallOption) (*NotificationsResponse, error) {
	out := new(NotificationsResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/RequestNotifications", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SetNotificationsSignal(ctx context.Context, in *NotificationsSignalPayload, opts ...grpc.CallOption) (*NotificationsSignalResponse, error) {
	out := new(NotificationsSignalResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SetNotificationsSignal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SetOnboardComplete(ctx context.Context, in *OnboardCompleteRequest, opts ...grpc.CallOption) (*OnboardCompleteResponse, error) {
	out := new(OnboardCompleteResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SetOnboardComplete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendAddress(ctx context.Context, in *SendAddressPayload, opts ...grpc.CallOption) (*SendAddressResponse, error) {
	out := new(SendAddressResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendFEConfigChanges(ctx context.Context, in *FEConfigChangesPayload, opts ...grpc.CallOption) (*FEConfigChangesResponse, error) {
	out := new(FEConfigChangesResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendFEConfigChanges", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) RequestBoardReports(ctx context.Context, in *BoardReportsRequest, opts ...grpc.CallOption) (*BoardReportsResponse, error) {
	out := new(BoardReportsResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/RequestBoardReports", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendMintedUsernames(ctx context.Context, in *SendMintedUsernamesPayload, opts ...grpc.CallOption) (*SendMintedUsernamesResponse, error) {
	out := new(SendMintedUsernamesResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendMintedUsernames", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendClientVersion(ctx context.Context, in *ClientVersionPayload, opts ...grpc.CallOption) (*ClientVersionResponse, error) {
	out := new(ClientVersionResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendClientVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendSearchRequest(ctx context.Context, in *SearchRequestPayload, opts ...grpc.CallOption) (*SearchRequestResponse, error) {
	out := new(SearchRequestResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendSearchRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) BackendReady(ctx context.Context, in *BEReadyRequest, opts ...grpc.CallOption) (*BEReadyResponse, error) {
	out := new(BEReadyResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/BackendReady", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendAPIClient) SendBackendAmbientStatus(ctx context.Context, in *BackendAmbientStatusPayload, opts ...grpc.CallOption) (*BackendAmbientStatusResponse, error) {
	out := new(BackendAmbientStatusResponse)
	err := grpc.Invoke(ctx, "/feapi.FrontendAPI/SendBackendAmbientStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FrontendAPI service

type FrontendAPIServer interface {
	// ----------  Methods used by client  ----------
	SetClientAPIServerPort(context.Context, *SetClientAPIServerPortRequest) (*SetClientAPIServerPortResponse, error)
	GetThreadAndPosts(context.Context, *ThreadAndPostsRequest) (*ThreadAndPostsResponse, error)
	GetBoardAndThreads(context.Context, *BoardAndThreadsRequest) (*BoardAndThreadsResponse, error)
	GetAllBoards(context.Context, *AllBoardsRequest) (*AllBoardsResponse, error)
	SetBoardSignal(context.Context, *BoardSignalRequest) (*BoardSignalResponse, error)
	GetUserAndGraph(context.Context, *UserAndGraphRequest) (*UserAndGraphResponse, error)
	SendContentEvent(context.Context, *ContentEventPayload) (*ContentEventResponse, error)
	SendSignalEvent(context.Context, *SignalEventPayload) (*SignalEventResponse, error)
	GetUncompiledEntityByKey(context.Context, *UncompiledEntityByKeyRequest) (*UncompiledEntityByKeyResponse, error)
	SendInflightsPruneRequest(context.Context, *InflightsPruneRequest) (*InflightsPruneResponse, error)
	RequestAmbientStatus(context.Context, *AmbientStatusRequest) (*AmbientStatusResponse, error)
	// ^ Client requests ambient status to be sent in.
	RequestHomeView(context.Context, *HomeViewRequest) (*HomeViewResponse, error)
	RequestPopularView(context.Context, *PopularViewRequest) (*PopularViewResponse, error)
	RequestNotifications(context.Context, *NotificationsRequest) (*NotificationsResponse, error)
	SetNotificationsSignal(context.Context, *NotificationsSignalPayload) (*NotificationsSignalResponse, error)
	// rpc RequestOnboardCompleteStatus(OnboardCompleteStatusRequest) returns (OnboardCompleteStatusResponse) {}
	SetOnboardComplete(context.Context, *OnboardCompleteRequest) (*OnboardCompleteResponse, error)
	SendAddress(context.Context, *SendAddressPayload) (*SendAddressResponse, error)
	SendFEConfigChanges(context.Context, *FEConfigChangesPayload) (*FEConfigChangesResponse, error)
	RequestBoardReports(context.Context, *BoardReportsRequest) (*BoardReportsResponse, error)
	SendMintedUsernames(context.Context, *SendMintedUsernamesPayload) (*SendMintedUsernamesResponse, error)
	SendClientVersion(context.Context, *ClientVersionPayload) (*ClientVersionResponse, error)
	SendSearchRequest(context.Context, *SearchRequestPayload) (*SearchRequestResponse, error)
	// ----------  Methods used by backend  ----------
	BackendReady(context.Context, *BEReadyRequest) (*BEReadyResponse, error)
	SendBackendAmbientStatus(context.Context, *BackendAmbientStatusPayload) (*BackendAmbientStatusResponse, error)
}

func RegisterFrontendAPIServer(s *grpc.Server, srv FrontendAPIServer) {
	s.RegisterService(&_FrontendAPI_serviceDesc, srv)
}

func _FrontendAPI_SetClientAPIServerPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClientAPIServerPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SetClientAPIServerPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SetClientAPIServerPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SetClientAPIServerPort(ctx, req.(*SetClientAPIServerPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_GetThreadAndPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreadAndPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).GetThreadAndPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/GetThreadAndPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).GetThreadAndPosts(ctx, req.(*ThreadAndPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_GetBoardAndThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardAndThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).GetBoardAndThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/GetBoardAndThreads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).GetBoardAndThreads(ctx, req.(*BoardAndThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_GetAllBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllBoardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).GetAllBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/GetAllBoards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).GetAllBoards(ctx, req.(*AllBoardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SetBoardSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SetBoardSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SetBoardSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SetBoardSignal(ctx, req.(*BoardSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_GetUserAndGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAndGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).GetUserAndGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/GetUserAndGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).GetUserAndGraph(ctx, req.(*UserAndGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendContentEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentEventPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendContentEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendContentEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendContentEvent(ctx, req.(*ContentEventPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendSignalEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalEventPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendSignalEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendSignalEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendSignalEvent(ctx, req.(*SignalEventPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_GetUncompiledEntityByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UncompiledEntityByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).GetUncompiledEntityByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/GetUncompiledEntityByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).GetUncompiledEntityByKey(ctx, req.(*UncompiledEntityByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendInflightsPruneRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InflightsPruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendInflightsPruneRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendInflightsPruneRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendInflightsPruneRequest(ctx, req.(*InflightsPruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_RequestAmbientStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AmbientStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).RequestAmbientStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/RequestAmbientStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).RequestAmbientStatus(ctx, req.(*AmbientStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_RequestHomeView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).RequestHomeView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/RequestHomeView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).RequestHomeView(ctx, req.(*HomeViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_RequestPopularView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopularViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).RequestPopularView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/RequestPopularView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).RequestPopularView(ctx, req.(*PopularViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_RequestNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).RequestNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/RequestNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).RequestNotifications(ctx, req.(*NotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SetNotificationsSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationsSignalPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SetNotificationsSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SetNotificationsSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SetNotificationsSignal(ctx, req.(*NotificationsSignalPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SetOnboardComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SetOnboardComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SetOnboardComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SetOnboardComplete(ctx, req.(*OnboardCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAddressPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendAddress(ctx, req.(*SendAddressPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendFEConfigChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FEConfigChangesPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendFEConfigChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendFEConfigChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendFEConfigChanges(ctx, req.(*FEConfigChangesPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_RequestBoardReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).RequestBoardReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/RequestBoardReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).RequestBoardReports(ctx, req.(*BoardReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendMintedUsernames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMintedUsernamesPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendMintedUsernames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendMintedUsernames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendMintedUsernames(ctx, req.(*SendMintedUsernamesPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendClientVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientVersionPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendClientVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendClientVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendClientVersion(ctx, req.(*ClientVersionPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendSearchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequestPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendSearchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendSearchRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendSearchRequest(ctx, req.(*SearchRequestPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_BackendReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BEReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).BackendReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/BackendReady",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).BackendReady(ctx, req.(*BEReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendAPI_SendBackendAmbientStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackendAmbientStatusPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendAPIServer).SendBackendAmbientStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feapi.FrontendAPI/SendBackendAmbientStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendAPIServer).SendBackendAmbientStatus(ctx, req.(*BackendAmbientStatusPayload))
	}
	return interceptor(ctx, in, info, handler)
}

var _FrontendAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feapi.FrontendAPI",
	HandlerType: (*FrontendAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetClientAPIServerPort",
			Handler:    _FrontendAPI_SetClientAPIServerPort_Handler,
		},
		{
			MethodName: "GetThreadAndPosts",
			Handler:    _FrontendAPI_GetThreadAndPosts_Handler,
		},
		{
			MethodName: "GetBoardAndThreads",
			Handler:    _FrontendAPI_GetBoardAndThreads_Handler,
		},
		{
			MethodName: "GetAllBoards",
			Handler:    _FrontendAPI_GetAllBoards_Handler,
		},
		{
			MethodName: "SetBoardSignal",
			Handler:    _FrontendAPI_SetBoardSignal_Handler,
		},
		{
			MethodName: "GetUserAndGraph",
			Handler:    _FrontendAPI_GetUserAndGraph_Handler,
		},
		{
			MethodName: "SendContentEvent",
			Handler:    _FrontendAPI_SendContentEvent_Handler,
		},
		{
			MethodName: "SendSignalEvent",
			Handler:    _FrontendAPI_SendSignalEvent_Handler,
		},
		{
			MethodName: "GetUncompiledEntityByKey",
			Handler:    _FrontendAPI_GetUncompiledEntityByKey_Handler,
		},
		{
			MethodName: "SendInflightsPruneRequest",
			Handler:    _FrontendAPI_SendInflightsPruneRequest_Handler,
		},
		{
			MethodName: "RequestAmbientStatus",
			Handler:    _FrontendAPI_RequestAmbientStatus_Handler,
		},
		{
			MethodName: "RequestHomeView",
			Handler:    _FrontendAPI_RequestHomeView_Handler,
		},
		{
			MethodName: "RequestPopularView",
			Handler:    _FrontendAPI_RequestPopularView_Handler,
		},
		{
			MethodName: "RequestNotifications",
			Handler:    _FrontendAPI_RequestNotifications_Handler,
		},
		{
			MethodName: "SetNotificationsSignal",
			Handler:    _FrontendAPI_SetNotificationsSignal_Handler,
		},
		{
			MethodName: "SetOnboardComplete",
			Handler:    _FrontendAPI_SetOnboardComplete_Handler,
		},
		{
			MethodName: "SendAddress",
			Handler:    _FrontendAPI_SendAddress_Handler,
		},
		{
			MethodName: "SendFEConfigChanges",
			Handler:    _FrontendAPI_SendFEConfigChanges_Handler,
		},
		{
			MethodName: "RequestBoardReports",
			Handler:    _FrontendAPI_RequestBoardReports_Handler,
		},
		{
			MethodName: "SendMintedUsernames",
			Handler:    _FrontendAPI_SendMintedUsernames_Handler,
		},
		{
			MethodName: "SendClientVersion",
			Handler:    _FrontendAPI_SendClientVersion_Handler,
		},
		{
			MethodName: "SendSearchRequest",
			Handler:    _FrontendAPI_SendSearchRequest_Handler,
		},
		{
			MethodName: "BackendReady",
			Handler:    _FrontendAPI_BackendReady_Handler,
		},
		{
			MethodName: "SendBackendAmbientStatus",
			Handler:    _FrontendAPI_SendBackendAmbientStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feapi/feapi.proto",
}

func init() { proto.RegisterFile("feapi/feapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0xcd, 0x72, 0xdb, 0xc8,
	0xf1, 0xe7, 0xa7, 0x3e, 0x5a, 0xb2, 0x05, 0x8d, 0x28, 0x8a, 0xa6, 0x65, 0x59, 0x8b, 0xf5, 0xfe,
	0x4b, 0xa5, 0xfd, 0x47, 0x5e, 0xcb, 0x8e, 0x53, 0xc9, 0xa6, 0x92, 0x40, 0x24, 0x24, 0xd3, 0x22,
	0x09, 0x1a, 0x00, 0xe5, 0x68, 0x0f, 0x51, 0x20, 0x71, 0x24, 0x23, 0x21, 0x01, 0x2e, 0x00, 0xad,
	0xcd, 0x57, 0xc8, 0x29, 0xcf, 0x91, 0xaa, 0xe4, 0x96, 0x43, 0xaa, 0xf2, 0x34, 0xfb, 0x04, 0x39,
	0xe5, 0x9a, 0xd4, 0x7c, 0x60, 0x08, 0x80, 0x43, 0x7f, 0xec, 0x56, 0xe5, 0xc2, 0xc2, 0x74, 0xff,
	0xba, 0xa7, 0xbb, 0x67, 0xa6, 0xa7, 0x7b, 0x08, 0xeb, 0xd7, 0xd8, 0x19, 0xbb, 0x8f, 0xe9, 0xef,
	0xc1, 0x38, 0xf0, 0x23, 0x1f, 0x95, 0xe9, 0xa0, 0x7e, 0xef, 0x1a, 0xfb, 0x97, 0x7f, 0xc0, 0x57,
	0x51, 0xf8, 0x58, 0x7c, 0x31, 0x44, 0xfd, 0xde, 0xc8, 0x1d, 0x11, 0xa9, 0x30, 0x0a, 0x6e, 0xaf,
	0x22, 0x4a, 0xe3, 0x2c, 0xf5, 0x57, 0x70, 0xf7, 0x48, 0x37, 0xb1, 0x33, 0x98, 0x98, 0xf8, 0xdb,
	0x5b, 0x1c, 0x46, 0xa8, 0x06, 0x8b, 0xce, 0x60, 0x10, 0xe0, 0x30, 0xac, 0xe5, 0x77, 0xf3, 0x7b,
	0xcb, 0x66, 0x3c, 0x44, 0x08, 0x4a, 0x63, 0x3f, 0x88, 0x6a, 0x85, 0xdd, 0xfc, 0x5e, 0xd9, 0xa4,
	0xdf, 0xea, 0x3a, 0xac, 0x09, 0xf9, 0x70, 0xec, 0x7b, 0x21, 0x56, 0x9f, 0xc2, 0x03, 0x0b, 0x47,
	0x8d, 0xa1, 0x8b, 0xbd, 0x48, 0xeb, 0xb5, 0x2c, 0x1c, 0x7c, 0x87, 0x83, 0x9e, 0x1f, 0x44, 0xf1,
	0x0c, 0x08, 0x4a, 0x64, 0x48, 0xd5, 0x97, 0x4d, 0xfa, 0xad, 0xee, 0xc2, 0xce, 0x3c, 0x21, 0xae,
	0x16, 0x81, 0xa2, 0x0d, 0x87, 0x47, 0xbe, 0x13, 0x0c, 0x42, 0xae, 0x49, 0x7d, 0x05, 0xeb, 0x09,
	0x1a, 0x03, 0xa2, 0x5f, 0xc2, 0xb2, 0x20, 0xd6, 0xf2, 0xbb, 0xc5, 0xbd, 0x95, 0xc3, 0x9d, 0x83,
	0x69, 0x48, 0x1a, 0xfe, 0x68, 0xec, 0x0e, 0xf1, 0x80, 0x02, 0x74, 0x2f, 0x72, 0xa3, 0x89, 0x39,
	0x15, 0x50, 0xbf, 0x85, 0x4d, 0xfb, 0x4d, 0x80, 0x9d, 0x81, 0xe6, 0x0d, 0x7a, 0x7e, 0x18, 0xc5,
	0x73, 0xa1, 0x7d, 0x50, 0x28, 0xe4, 0xd8, 0xf5, 0x6e, 0x70, 0x30, 0x0e, 0x5c, 0x2f, 0xe2, 0x01,
	0x9a, 0xa1, 0xa3, 0xff, 0x87, 0x75, 0xa6, 0x24, 0x09, 0x2e, 0x50, 0xf0, 0x2c, 0x43, 0xfd, 0x67,
	0x1e, 0xaa, 0xd9, 0x39, 0xb9, 0x2f, 0xcf, 0xa0, 0x4c, 0x95, 0xd3, 0x99, 0x3e, 0xec, 0x07, 0x03,
	0xa3, 0x9f, 0xc1, 0x02, 0xd3, 0x47, 0xe7, 0x5c, 0x39, 0x7c, 0x28, 0x11, 0x63, 0x00, 0x2e, 0xc7,
	0xe1, 0xe8, 0x29, 0x94, 0xe9, 0xfc, 0xb5, 0x22, 0x0d, 0xdb, 0x03, 0x89, 0x1c, 0xe1, 0xc7, 0xb3,
	0x51, 0xac, 0x3a, 0x86, 0x2a, 0x9d, 0x56, 0xf3, 0xb8, 0xd2, 0x1f, 0x14, 0xb2, 0x7d, 0x50, 0x2c,
	0x3f, 0x88, 0xb8, 0x86, 0xa3, 0x49, 0x17, 0xbf, 0xa5, 0xd6, 0x2f, 0x99, 0x33, 0x74, 0xf5, 0x4f,
	0x79, 0xd8, 0x9a, 0x99, 0xf2, 0x47, 0x45, 0xec, 0xe7, 0xb0, 0xc8, 0x15, 0xd5, 0x0a, 0xd4, 0xf5,
	0x0f, 0x86, 0x2c, 0xc6, 0xab, 0x7f, 0xcb, 0x03, 0xa2, 0x4a, 0x2c, 0xf7, 0xc6, 0x73, 0x86, 0xb1,
	0xef, 0xbb, 0xb0, 0x32, 0xeb, 0x76, 0x92, 0x84, 0x76, 0x00, 0xac, 0xdb, 0xcb, 0xf0, 0x2a, 0x70,
	0x2f, 0xf1, 0x80, 0xfb, 0x9a, 0xa0, 0xa0, 0x2a, 0x2c, 0x74, 0xfd, 0xc8, 0xbd, 0x9e, 0xd4, 0x8a,
	0x94, 0xc7, 0x47, 0xa8, 0x0e, 0x4b, 0x6d, 0x27, 0x8c, 0x2c, 0x8c, 0xbd, 0x5a, 0x69, 0x37, 0xbf,
	0x57, 0x34, 0xc5, 0x18, 0xa9, 0xb0, 0x1a, 0x7f, 0x1b, 0xde, 0x70, 0x52, 0x2b, 0x53, 0xc9, 0x14,
	0x4d, 0x7d, 0x0a, 0x1b, 0x29, 0x7b, 0x79, 0xe0, 0xb6, 0x61, 0xb9, 0xe1, 0x8f, 0x46, 0x6e, 0x14,
	0x61, 0x16, 0xbc, 0x25, 0x73, 0x4a, 0x50, 0xff, 0x93, 0x87, 0x8d, 0x7e, 0x88, 0x03, 0xcd, 0x1b,
	0x9c, 0x04, 0xce, 0xf8, 0xcd, 0xc7, 0xbb, 0xf9, 0x15, 0x13, 0xe4, 0x61, 0x63, 0x62, 0xc2, 0x5f,
	0x19, 0x2b, 0x96, 0x48, 0x1d, 0x75, 0x3c, 0xa8, 0x2d, 0x4c, 0x25, 0x32, 0x2c, 0x74, 0x08, 0x15,
	0x42, 0x4e, 0x6f, 0x3f, 0x3c, 0xa0, 0xe1, 0x59, 0x32, 0xa5, 0x3c, 0x74, 0x00, 0x88, 0xd0, 0x93,
	0x67, 0x1c, 0x0f, 0x78, 0xc0, 0x24, 0x1c, 0xf5, 0x1f, 0x45, 0x36, 0xc9, 0x34, 0x02, 0x3c, 0x70,
	0x4f, 0xa0, 0x44, 0xe8, 0x7c, 0xc3, 0xc9, 0xce, 0x4c, 0xc2, 0x49, 0x0a, 0x45, 0xcf, 0x61, 0x81,
	0xe7, 0xa7, 0xc2, 0x47, 0xe5, 0x27, 0x8e, 0x4e, 0x6e, 0xd3, 0xe2, 0xa7, 0x6d, 0xd3, 0xe9, 0xd1,
	0x2e, 0x7d, 0xfc, 0xd1, 0x9e, 0xb7, 0x76, 0xe5, 0xff, 0xc5, 0xda, 0x2d, 0x7e, 0xf2, 0xda, 0x2d,
	0xcd, 0x5d, 0xbb, 0xbf, 0xe6, 0xa1, 0xac, 0x7f, 0x87, 0x59, 0x9a, 0x31, 0xde, 0x7a, 0x38, 0x90,
	0xa4, 0xa4, 0x2c, 0x9d, 0x60, 0x7b, 0x81, 0xeb, 0x07, 0xb3, 0x49, 0x7c, 0x86, 0x8e, 0x0e, 0x60,
	0x99, 0x4e, 0x60, 0x4f, 0xc6, 0x98, 0x9e, 0xd7, 0xbb, 0x87, 0xca, 0x01, 0xbb, 0xa5, 0x05, 0xdd,
	0x9c, 0x42, 0xc8, 0x69, 0xb3, 0xdd, 0x11, 0x0e, 0x23, 0x67, 0x34, 0xe6, 0xa7, 0x78, 0x4a, 0xa0,
	0xa7, 0xad, 0xe1, 0x7b, 0x11, 0xf6, 0x22, 0x2a, 0xd2, 0x73, 0x26, 0x43, 0xdf, 0x19, 0x20, 0x95,
	0xbb, 0xc1, 0xf7, 0xda, 0x6a, 0x72, 0x06, 0x93, 0x7b, 0xf8, 0x04, 0x96, 0x69, 0x88, 0x9b, 0x4e,
	0xe4, 0xf0, 0xfc, 0xbf, 0x71, 0x90, 0xba, 0xf9, 0x29, 0xdb, 0x9c, 0xa2, 0xd0, 0x33, 0x00, 0x16,
	0x62, 0x2a, 0x53, 0xa4, 0x32, 0x95, 0xb4, 0x0c, 0xe3, 0x9b, 0x09, 0x1c, 0x3a, 0x80, 0x25, 0x12,
	0x66, 0x2a, 0x53, 0xa2, 0x32, 0x28, 0x2d, 0x43, 0xb8, 0xa6, 0xc0, 0xa0, 0x2f, 0x61, 0xf1, 0x14,
	0x4f, 0x28, 0xbc, 0x4c, 0xe1, 0xeb, 0x69, 0xf8, 0x29, 0x9e, 0x98, 0x31, 0x42, 0xad, 0x42, 0x25,
	0x19, 0x00, 0x51, 0x05, 0x7c, 0x5f, 0x04, 0xc4, 0x12, 0xd7, 0x27, 0x07, 0xa6, 0x01, 0x0a, 0x93,
	0xb4, 0x9d, 0xe0, 0x06, 0xb3, 0x95, 0x2a, 0xd0, 0x95, 0xda, 0xe2, 0xf0, 0x2c, 0xdb, 0x9c, 0x11,
	0x20, 0xf9, 0x8e, 0x8d, 0xd8, 0x25, 0x53, 0x64, 0xf9, 0x2e, 0x41, 0x22, 0x29, 0x98, 0xe3, 0xd9,
	0x15, 0x5c, 0xa2, 0x90, 0x14, 0x6d, 0x8a, 0x69, 0xfa, 0x23, 0xc7, 0xf5, 0x68, 0x3c, 0x04, 0x86,
	0xd1, 0xa6, 0x18, 0xfd, 0xdd, 0xd8, 0x0d, 0x26, 0xf4, 0x08, 0x15, 0xcd, 0x14, 0x8d, 0x54, 0x52,
	0x1d, 0x1c, 0x39, 0xf4, 0xac, 0x2c, 0x9b, 0xf4, 0x9b, 0xd6, 0x1e, 0x14, 0x93, 0xdc, 0xb6, 0x4b,
	0xbc, 0xf6, 0xc8, 0x32, 0xd0, 0x6f, 0x60, 0x8d, 0xfb, 0x38, 0x19, 0xe3, 0xc6, 0xd0, 0x09, 0xc3,
	0xda, 0x32, 0x8d, 0x49, 0x35, 0x1d, 0x93, 0x98, 0x6b, 0x66, 0xe1, 0xe8, 0x09, 0xc0, 0x94, 0x54,
	0x03, 0x2a, 0xbc, 0x3e, 0x23, 0x6c, 0x26, 0x40, 0xf4, 0xe6, 0x63, 0x23, 0xfc, 0x2e, 0xaa, 0xad,
	0x50, 0xdb, 0x12, 0x14, 0x75, 0x13, 0x36, 0x12, 0x6b, 0x2c, 0xd6, 0xfe, 0xef, 0x79, 0xd8, 0xee,
	0x7b, 0x57, 0x3c, 0x5b, 0xb1, 0xcc, 0x73, 0x34, 0x21, 0xdb, 0x86, 0x5f, 0x46, 0x5f, 0x03, 0x30,
	0x2a, 0x35, 0x25, 0x4f, 0x4d, 0xb9, 0xcf, 0x4d, 0xc9, 0x0a, 0x32, 0xa3, 0xa6, 0xdf, 0xa8, 0x02,
	0xe5, 0xb6, 0x3b, 0x72, 0xe3, 0xf2, 0x96, 0x0d, 0xc8, 0x25, 0x6c, 0x5c, 0x5f, 0x87, 0x38, 0xa2,
	0x4b, 0x5d, 0x36, 0xf9, 0x48, 0x9a, 0x47, 0x4a, 0xf2, 0x3c, 0xa2, 0xfe, 0xab, 0x00, 0x0f, 0xe6,
	0xd8, 0xcd, 0xaf, 0x90, 0x1f, 0x65, 0xf8, 0x97, 0x99, 0xcb, 0x44, 0x7a, 0xda, 0xe3, 0x1b, 0xe4,
	0x20, 0x7b, 0x83, 0xc8, 0xcf, 0xb9, 0xb8, 0x36, 0xf6, 0xd2, 0xd7, 0x86, 0xec, 0x84, 0xf3, 0xbb,
	0x62, 0x0f, 0xca, 0x67, 0x7e, 0x84, 0xc3, 0x5a, 0x59, 0x86, 0x24, 0x2c, 0x93, 0x01, 0xd0, 0x17,
	0x50, 0x3a, 0xc5, 0x93, 0xb0, 0xb6, 0x40, 0x81, 0x92, 0x2c, 0x40, 0xd9, 0xe8, 0x17, 0xb0, 0x62,
	0x07, 0xb7, 0x61, 0x14, 0x46, 0x0e, 0x51, 0xbb, 0x48, 0xd1, 0xb5, 0x8c, 0xb9, 0x02, 0x60, 0x26,
	0xc1, 0xea, 0x16, 0x6c, 0xb6, 0xbc, 0xeb, 0xa1, 0x7b, 0xf3, 0x26, 0x0a, 0x7b, 0xc1, 0xad, 0x87,
	0xe3, 0x8e, 0xa1, 0x06, 0xd5, 0x2c, 0x83, 0xef, 0xae, 0x00, 0xee, 0x1f, 0x39, 0x57, 0x7f, 0xc4,
	0xde, 0x40, 0x1b, 0x5d, 0x92, 0x36, 0xc4, 0x8a, 0x9c, 0xe8, 0x36, 0x8c, 0x33, 0x8c, 0x05, 0x15,
	0x19, 0x9b, 0x27, 0x9c, 0xe4, 0x3d, 0x2c, 0x83, 0x99, 0x52, 0x61, 0x75, 0x07, 0xb6, 0xa5, 0xe8,
	0xd8, 0xa6, 0x2a, 0x54, 0x32, 0x0c, 0xe6, 0xc5, 0x16, 0x6c, 0xca, 0x05, 0xd6, 0x61, 0xed, 0x85,
	0x3f, 0xc2, 0x67, 0x2e, 0x7e, 0x1b, 0x63, 0x11, 0x28, 0x53, 0x12, 0x87, 0x55, 0x00, 0xf5, 0xfc,
	0xf1, 0xed, 0xd0, 0x09, 0x92, 0xc8, 0x4d, 0xd8, 0x48, 0x51, 0xa7, 0x46, 0xd0, 0xca, 0xd3, 0xbd,
	0x72, 0x22, 0xd7, 0xf7, 0x92, 0x46, 0x64, 0xe8, 0x5c, 0xe0, 0x12, 0xea, 0x29, 0x06, 0x3b, 0xcb,
	0x71, 0x20, 0x11, 0x94, 0x68, 0xe9, 0xca, 0x4a, 0x4c, 0xfa, 0x4d, 0xaa, 0x06, 0xd2, 0x43, 0xb6,
	0x22, 0x3c, 0x9a, 0xbd, 0x6c, 0x65, 0x2c, 0xf5, 0x01, 0xdc, 0x97, 0xcc, 0x21, 0x4c, 0x38, 0x82,
	0xaa, 0xe1, 0x5d, 0x92, 0x2d, 0x4f, 0x8a, 0x9b, 0x21, 0x8e, 0xe2, 0x0d, 0x80, 0xf6, 0x60, 0x2d,
	0xc3, 0xe1, 0x96, 0x64, 0xc9, 0xea, 0x3d, 0xd8, 0x9a, 0xd1, 0xc1, 0xd5, 0xeb, 0x80, 0x2c, 0xb2,
	0x68, 0xac, 0x31, 0x8e, 0x3d, 0x7b, 0x0c, 0x8b, 0x5a, 0xa2, 0x73, 0x5e, 0x39, 0xdc, 0x4c, 0x6f,
	0x56, 0xce, 0x34, 0x63, 0x94, 0x7a, 0x0e, 0x1b, 0x09, 0x35, 0x22, 0x1b, 0x90, 0xf4, 0x48, 0x97,
	0xb5, 0xe1, 0x0f, 0x30, 0xef, 0x92, 0x13, 0x14, 0x72, 0x33, 0xe8, 0x41, 0xe0, 0x07, 0x1d, 0x1c,
	0x86, 0xce, 0x0d, 0xe6, 0x61, 0x4a, 0xd1, 0xd4, 0x3f, 0x17, 0xa0, 0x7a, 0xac, 0x37, 0x7c, 0xef,
	0xda, 0xbd, 0x69, 0xbc, 0x71, 0xbc, 0x1b, 0x2c, 0xcc, 0xfc, 0x0a, 0x36, 0x3a, 0xfe, 0xa0, 0xe3,
	0x0f, 0xb0, 0xee, 0x39, 0x97, 0x43, 0x3c, 0x68, 0x85, 0x16, 0x8e, 0x78, 0x14, 0x64, 0x2c, 0xf4,
	0x7f, 0x70, 0x37, 0x4d, 0xe6, 0xd5, 0x7b, 0x86, 0x8a, 0x5e, 0xc0, 0x43, 0xfd, 0x5d, 0x84, 0x03,
	0xcf, 0x19, 0xf2, 0xcb, 0x5b, 0xbb, 0x8d, 0x7c, 0x32, 0x69, 0xd3, 0x0d, 0x99, 0x20, 0x6b, 0x65,
	0x3e, 0x04, 0x43, 0x26, 0x3c, 0xfa, 0x00, 0x84, 0x19, 0xcd, 0x0a, 0xfc, 0x8f, 0xc2, 0x92, 0xf5,
	0xcc, 0x44, 0x44, 0xac, 0xa7, 0xc6, 0x5b, 0x22, 0x13, 0x8f, 0xfd, 0xe0, 0x07, 0xb5, 0xfc, 0xea,
	0xef, 0xa1, 0x92, 0x56, 0xc1, 0x17, 0xf3, 0x05, 0xac, 0x73, 0x92, 0xed, 0x5c, 0xea, 0x5e, 0x14,
	0xb8, 0x38, 0x7e, 0x95, 0xa8, 0x27, 0x92, 0x46, 0x1a, 0x33, 0x31, 0x67, 0x85, 0x54, 0x1b, 0xea,
	0x64, 0xb7, 0x74, 0x5c, 0x2f, 0x62, 0x2d, 0x85, 0xe7, 0x8c, 0xa6, 0xab, 0xfa, 0x1c, 0xaa, 0x19,
	0x8e, 0xe9, 0xbc, 0x7d, 0x69, 0x19, 0x5d, 0x6e, 0xf1, 0x1c, 0x2e, 0x39, 0x48, 0x12, 0xad, 0x22,
	0x32, 0x2f, 0xa1, 0xc2, 0x1e, 0x65, 0xce, 0x70, 0x10, 0xba, 0xbe, 0x17, 0x4f, 0x77, 0x08, 0x95,
	0xc6, 0x6d, 0x10, 0x60, 0x2f, 0x4a, 0xb1, 0xf9, 0x64, 0x52, 0x9e, 0x6a, 0xc0, 0x66, 0x8a, 0x20,
	0x62, 0xf4, 0x1c, 0xaa, 0xa4, 0x43, 0x3d, 0xf5, 0xfc, 0xb7, 0x9e, 0x4c, 0xdd, 0x1c, 0xae, 0xfa,
	0x5b, 0xa8, 0x58, 0xd8, 0x09, 0xae, 0xe2, 0x6e, 0x34, 0x36, 0x8e, 0x1c, 0x20, 0x4a, 0x17, 0xd7,
	0x29, 0xa9, 0x2f, 0x04, 0x85, 0x14, 0x71, 0x6c, 0xf4, 0xea, 0x16, 0x07, 0x13, 0x7e, 0x7e, 0x92,
	0x24, 0x92, 0xdb, 0x52, 0x9a, 0x63, 0x53, 0xf7, 0xbf, 0x4e, 0xd4, 0xf9, 0xa8, 0x0a, 0xa8, 0xdf,
	0x3d, 0xed, 0x1a, 0xaf, 0xbb, 0x17, 0xfa, 0x99, 0xde, 0xb5, 0x2f, 0xec, 0xf3, 0x9e, 0xae, 0xe4,
	0x10, 0xc0, 0x42, 0xc3, 0xd4, 0x35, 0x5b, 0x57, 0xf2, 0xe4, 0xbb, 0xdf, 0x6b, 0x92, 0xef, 0xc2,
	0x7e, 0x6b, 0xb6, 0x02, 0x45, 0x3b, 0x50, 0x8f, 0x75, 0x58, 0xad, 0x93, 0xae, 0xd6, 0xbe, 0xb0,
	0x35, 0xf3, 0x44, 0x17, 0xba, 0x56, 0x60, 0xb1, 0x61, 0x74, 0x6d, 0xbd, 0x6b, 0x2b, 0x79, 0xb4,
	0x04, 0xa5, 0xbe, 0xa5, 0x9b, 0x4a, 0x61, 0xff, 0x2f, 0xf9, 0x99, 0xc2, 0x0d, 0x6d, 0x43, 0x2d,
	0xab, 0xea, 0xbc, 0xa7, 0x37, 0xda, 0x9a, 0x65, 0x29, 0x39, 0x62, 0xac, 0xd6, 0x6c, 0x5a, 0x17,
	0xb6, 0x71, 0xd1, 0x6c, 0x59, 0x8d, 0xbe, 0x65, 0xb5, 0x8c, 0xae, 0x92, 0x27, 0xf4, 0x63, 0xa3,
	0xdd, 0x36, 0x5e, 0x5b, 0x17, 0x27, 0xfd, 0x56, 0x53, 0x6f, 0xb7, 0xba, 0xba, 0xa5, 0x14, 0xd0,
	0x1a, 0xac, 0x74, 0x8c, 0xe6, 0x85, 0xd6, 0xb0, 0x5b, 0x46, 0xd7, 0x52, 0x8a, 0x48, 0x81, 0xd5,
	0x5e, 0xff, 0xa8, 0xdd, 0x6a, 0x5c, 0xd8, 0x66, 0xdf, 0xb2, 0x95, 0x12, 0xf1, 0xad, 0xab, 0x75,
	0x5a, 0xdd, 0x13, 0xa5, 0x4c, 0x4c, 0x3b, 0x7e, 0xf6, 0xd3, 0x27, 0xca, 0x42, 0x02, 0xa7, 0xb7,
	0xf5, 0x86, 0xad, 0x2c, 0xee, 0x7f, 0x9f, 0x4f, 0xd6, 0x88, 0x68, 0x0b, 0x36, 0x24, 0x76, 0xb2,
	0xb8, 0xf5, 0x7b, 0x67, 0x06, 0x8d, 0xdb, 0x2a, 0x2c, 0x35, 0x8d, 0xd7, 0x5d, 0x3a, 0x2a, 0xa0,
	0x75, 0xb8, 0x63, 0xea, 0x3d, 0xc3, 0xb4, 0x89, 0xf9, 0x1d, 0xa3, 0xa9, 0x14, 0x09, 0xa0, 0x63,
	0x34, 0x8f, 0xda, 0x46, 0xe3, 0x54, 0x29, 0xa1, 0xbb, 0x00, 0x1d, 0xa3, 0xa9, 0xf5, 0x7a, 0xa6,
	0x71, 0xa6, 0x2b, 0x65, 0x74, 0x07, 0x96, 0x3b, 0x46, 0xb3, 0x75, 0xd2, 0x35, 0x4c, 0x5d, 0x59,
	0x20, 0x9a, 0x99, 0x93, 0xca, 0x22, 0x5a, 0x86, 0x32, 0x93, 0x5a, 0x22, 0x3e, 0x76, 0xb5, 0x8e,
	0x7e, 0xa1, 0x59, 0xc4, 0x10, 0x65, 0x99, 0xcc, 0xd3, 0xd0, 0xbb, 0x96, 0x61, 0xc6, 0x24, 0x20,
	0x70, 0xe6, 0xc7, 0x0a, 0x99, 0xa4, 0xd9, 0xb2, 0x5e, 0xf5, 0xb5, 0x76, 0xeb, 0xf8, 0x5c, 0x59,
	0x25, 0x6b, 0x63, 0xea, 0xb6, 0xa9, 0x35, 0x6c, 0xe5, 0xce, 0x7e, 0x08, 0x15, 0x59, 0xa9, 0x96,
	0xf4, 0x56, 0xef, 0xda, 0x2d, 0xfb, 0x3c, 0xf6, 0x96, 0xd8, 0x61, 0x68, 0x66, 0x93, 0x6d, 0x12,
	0xfb, 0x85, 0xa9, 0x6b, 0x4d, 0xa5, 0x40, 0x02, 0xd9, 0x33, 0x2c, 0x5b, 0x29, 0x92, 0x2f, 0xea,
	0x7e, 0x09, 0x2d, 0x42, 0xf1, 0x54, 0x3f, 0x57, 0xca, 0xc4, 0x02, 0x1a, 0x7c, 0xcb, 0x26, 0x3b,
	0x6a, 0xe1, 0xf0, 0xdf, 0x6b, 0xb0, 0x72, 0x1c, 0xd0, 0xac, 0x37, 0xd0, 0x7a, 0x2d, 0x74, 0x03,
	0x55, 0xf9, 0x33, 0x2a, 0x7a, 0x14, 0x97, 0xe4, 0xef, 0x7b, 0x9a, 0xad, 0x7f, 0xf1, 0x01, 0x14,
	0xcf, 0x0a, 0x39, 0x64, 0xc2, 0xfa, 0x49, 0xdc, 0xce, 0xc4, 0xaf, 0x96, 0x68, 0x9b, 0x4b, 0x4b,
	0x1f, 0x50, 0xeb, 0x0f, 0xe6, 0x70, 0x85, 0xce, 0x3e, 0xa0, 0x13, 0xde, 0x45, 0x4d, 0x1f, 0xf6,
	0x50, 0x2c, 0x26, 0x7f, 0x63, 0xac, 0xef, 0xcc, 0x63, 0x0b, 0xb5, 0x0d, 0x58, 0x3d, 0xc1, 0x91,
	0x78, 0xe1, 0x45, 0x71, 0xb7, 0x97, 0x7d, 0x4d, 0xae, 0xd7, 0x66, 0x19, 0x42, 0x49, 0x0b, 0xee,
	0x5a, 0xdc, 0x36, 0xb6, 0x93, 0xd1, 0xbd, 0xe4, 0xc4, 0xa9, 0xb7, 0xbf, 0x7a, 0x5d, 0xc6, 0x12,
	0xaa, 0xda, 0xb0, 0x76, 0x82, 0xa3, 0xe4, 0x53, 0x12, 0x8a, 0x05, 0x24, 0x2f, 0x6c, 0xf5, 0xfb,
	0x52, 0x9e, 0xd0, 0xd6, 0x01, 0x85, 0xe4, 0xef, 0x64, 0xb3, 0x2c, 0xd4, 0x49, 0x9e, 0x10, 0x84,
	0x3a, 0x69, 0x77, 0x9d, 0x43, 0x2f, 0x61, 0x8d, 0xa8, 0x4b, 0xb4, 0x5f, 0xc2, 0xd1, 0xd9, 0xb6,
	0x5b, 0x38, 0x2a, 0xeb, 0xd6, 0x72, 0xe8, 0x06, 0x6a, 0xc4, 0x51, 0x59, 0xe7, 0x83, 0x3e, 0x9f,
	0xd3, 0xdd, 0x24, 0xfb, 0xb9, 0xfa, 0xa3, 0xf7, 0x83, 0xc4, 0x44, 0xdf, 0xc0, 0x3d, 0x62, 0xb4,
	0xb4, 0xe2, 0x17, 0x9b, 0x52, 0xca, 0x15, 0x9b, 0x72, 0x4e, 0x53, 0x90, 0x23, 0x75, 0x3f, 0xc7,
	0xa6, 0x2a, 0x6e, 0x14, 0xc7, 0x51, 0x56, 0x9f, 0xd7, 0xb7, 0xe5, 0x4c, 0xa1, 0xb4, 0x09, 0x6b,
	0x1c, 0x1a, 0x97, 0xe6, 0x28, 0xee, 0xb7, 0x33, 0xe5, 0x7b, 0x7d, 0x6b, 0x86, 0x9e, 0x58, 0x7a,
	0x14, 0x5f, 0x7c, 0xd3, 0xb2, 0x5d, 0x2c, 0xd7, 0x6c, 0x81, 0x2f, 0x96, 0x4b, 0x56, 0xe5, 0x27,
	0x3d, 0x4d, 0x55, 0xd6, 0xc2, 0x53, 0x59, 0x13, 0x20, 0x3c, 0x95, 0x77, 0x02, 0x39, 0xe4, 0xd0,
	0x84, 0x24, 0x29, 0xd5, 0xd1, 0x67, 0x32, 0xc9, 0x54, 0xab, 0x50, 0x57, 0xe7, 0x43, 0xd2, 0x69,
	0xc3, 0xc2, 0x51, 0xa6, 0x54, 0x17, 0x69, 0x43, 0xde, 0x06, 0x88, 0xb4, 0x31, 0xaf, 0xc2, 0xcf,
	0xa1, 0x63, 0x52, 0x24, 0x88, 0xe2, 0x7c, 0x7a, 0x0a, 0x66, 0xea, 0xfe, 0xe9, 0x29, 0x98, 0xad,
	0xe5, 0xd5, 0x1c, 0x3a, 0x63, 0x45, 0x7e, 0xa6, 0xf4, 0x14, 0xf6, 0xc9, 0x8b, 0x74, 0x61, 0xdf,
	0xbc, 0x8a, 0x35, 0x87, 0x7a, 0xa4, 0x67, 0xa2, 0xce, 0x24, 0xeb, 0x4e, 0x94, 0xca, 0x3d, 0xe9,
	0x7a, 0x56, 0x9c, 0x7d, 0x59, 0xa1, 0xaa, 0xe6, 0xd0, 0xef, 0x98, 0xa5, 0x99, 0x52, 0x50, 0x2c,
	0xd4, 0xfc, 0xe2, 0x53, 0x2c, 0xd4, 0xfb, 0x2a, 0x49, 0x62, 0xf1, 0x3a, 0x4d, 0x55, 0xc9, 0x1a,
	0x4e, 0xec, 0x2e, 0x59, 0x95, 0x29, 0x76, 0x97, 0xb4, 0x6c, 0x9c, 0x6a, 0x4c, 0x95, 0x6a, 0x42,
	0xa3, 0xac, 0x34, 0x14, 0x1a, 0xa5, 0xd5, 0x9d, 0x9a, 0x43, 0xbf, 0x86, 0x55, 0xde, 0x91, 0xd3,
	0x3f, 0x35, 0xd1, 0x66, 0x1c, 0xb2, 0xd4, 0x9f, 0xa4, 0xf5, 0x6a, 0x96, 0x2c, 0x14, 0x60, 0xa8,
	0x11, 0x93, 0x64, 0x6d, 0x3d, 0x8a, 0xc3, 0xf4, 0x9e, 0x77, 0x86, 0xfa, 0xe7, 0xef, 0xc1, 0x4c,
	0xa7, 0x39, 0xfa, 0xec, 0x9b, 0x87, 0x0e, 0x8e, 0xde, 0xe0, 0xe0, 0x27, 0x57, 0x7e, 0x80, 0x1f,
	0xb3, 0xef, 0xc7, 0xac, 0xd1, 0x64, 0xff, 0x0e, 0x5f, 0x2e, 0xd0, 0xd1, 0xd3, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x52, 0xaa, 0x10, 0x5c, 0x33, 0x1e, 0x00, 0x00,
}
