// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feobjects/feobjects.proto

/*
Package feobjects is a generated protocol buffer package.

It is generated from these files:
	feobjects/feobjects.proto

It has these top-level messages:
	CompiledBoardEntity
	CompiledThreadEntity
	CompiledPostEntity
	CompiledUserEntity
	CUserUsername
	CompiledContentSignalsEntity
	ExplainedSignalEntity
	CompiledUserSignalsEntity
	AmbientBoardEntity
	BackendAmbientStatus
	FrontendAmbientStatus
	CompiledNotification
	ReportsTabEntry
	ModActionsTabEntry
*/
package feobjects

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationType int32

const (
	NotificationType_UNKNOWN_NOTIFICATION_TYPE NotificationType = 0
	NotificationType_REPLY_TO_THREAD           NotificationType = 1
	NotificationType_REPLY_TO_POST             NotificationType = 2
)

var NotificationType_name = map[int32]string{
	0: "UNKNOWN_NOTIFICATION_TYPE",
	1: "REPLY_TO_THREAD",
	2: "REPLY_TO_POST",
}
var NotificationType_value = map[string]int32{
	"UNKNOWN_NOTIFICATION_TYPE": 0,
	"REPLY_TO_THREAD":           1,
	"REPLY_TO_POST":             2,
}

func (x NotificationType) String() string {
	return proto.EnumName(NotificationType_name, int32(x))
}
func (NotificationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CompiledBoardEntity struct {
	Fingerprint            string                        `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	SelfCreated            bool                          `protobuf:"varint,2,opt,name=SelfCreated" json:"SelfCreated,omitempty"`
	Name                   string                        `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Description            string                        `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	CompiledContentSignals *CompiledContentSignalsEntity `protobuf:"bytes,5,opt,name=CompiledContentSignals" json:"CompiledContentSignals,omitempty"`
	Owner                  *CompiledUserEntity           `protobuf:"bytes,6,opt,name=Owner" json:"Owner,omitempty"`
	BoardOwners            []string                      `protobuf:"bytes,7,rep,name=BoardOwners" json:"BoardOwners,omitempty"`
	Creation               int64                         `protobuf:"varint,8,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate             int64                         `protobuf:"varint,9,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	Meta                   string                        `protobuf:"bytes,10,opt,name=Meta" json:"Meta,omitempty"`
	ChildThreads           []*CompiledThreadEntity       `protobuf:"bytes,11,rep,name=ChildThreads" json:"ChildThreads,omitempty"`
	ThreadsCount           int32                         `protobuf:"varint,12,opt,name=ThreadsCount" json:"ThreadsCount,omitempty"`
	UserCount              int32                         `protobuf:"varint,13,opt,name=UserCount" json:"UserCount,omitempty"`
	Subscribed             bool                          `protobuf:"varint,14,opt,name=Subscribed" json:"Subscribed,omitempty"`
	Notify                 bool                          `protobuf:"varint,15,opt,name=Notify" json:"Notify,omitempty"`
	LastSeen               int64                         `protobuf:"varint,16,opt,name=LastSeen" json:"LastSeen,omitempty"`
	SFWListed              bool                          `protobuf:"varint,17,opt,name=SFWListed" json:"SFWListed,omitempty"`
	ViewMeta_SearchScore   float64                       `protobuf:"fixed64,18,opt,name=ViewMeta_SearchScore,json=ViewMetaSearchScore" json:"ViewMeta_SearchScore,omitempty"`
	LastNewThreadArrived   int64                         `protobuf:"varint,19,opt,name=LastNewThreadArrived" json:"LastNewThreadArrived,omitempty"`
}

func (m *CompiledBoardEntity) Reset()                    { *m = CompiledBoardEntity{} }
func (m *CompiledBoardEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledBoardEntity) ProtoMessage()               {}
func (*CompiledBoardEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CompiledBoardEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledBoardEntity) GetSelfCreated() bool {
	if m != nil {
		return m.SelfCreated
	}
	return false
}

func (m *CompiledBoardEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompiledBoardEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CompiledBoardEntity) GetCompiledContentSignals() *CompiledContentSignalsEntity {
	if m != nil {
		return m.CompiledContentSignals
	}
	return nil
}

func (m *CompiledBoardEntity) GetOwner() *CompiledUserEntity {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CompiledBoardEntity) GetBoardOwners() []string {
	if m != nil {
		return m.BoardOwners
	}
	return nil
}

func (m *CompiledBoardEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledBoardEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledBoardEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledBoardEntity) GetChildThreads() []*CompiledThreadEntity {
	if m != nil {
		return m.ChildThreads
	}
	return nil
}

func (m *CompiledBoardEntity) GetThreadsCount() int32 {
	if m != nil {
		return m.ThreadsCount
	}
	return 0
}

func (m *CompiledBoardEntity) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *CompiledBoardEntity) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

func (m *CompiledBoardEntity) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func (m *CompiledBoardEntity) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *CompiledBoardEntity) GetSFWListed() bool {
	if m != nil {
		return m.SFWListed
	}
	return false
}

func (m *CompiledBoardEntity) GetViewMeta_SearchScore() float64 {
	if m != nil {
		return m.ViewMeta_SearchScore
	}
	return 0
}

func (m *CompiledBoardEntity) GetLastNewThreadArrived() int64 {
	if m != nil {
		return m.LastNewThreadArrived
	}
	return 0
}

type CompiledThreadEntity struct {
	Fingerprint            string                        `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Board                  string                        `protobuf:"bytes,2,opt,name=Board" json:"Board,omitempty"`
	SelfCreated            bool                          `protobuf:"varint,3,opt,name=SelfCreated" json:"SelfCreated,omitempty"`
	Name                   string                        `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	Body                   string                        `protobuf:"bytes,5,opt,name=Body" json:"Body,omitempty"`
	Link                   string                        `protobuf:"bytes,6,opt,name=Link" json:"Link,omitempty"`
	CompiledContentSignals *CompiledContentSignalsEntity `protobuf:"bytes,7,opt,name=CompiledContentSignals" json:"CompiledContentSignals,omitempty"`
	Owner                  *CompiledUserEntity           `protobuf:"bytes,8,opt,name=Owner" json:"Owner,omitempty"`
	Creation               int64                         `protobuf:"varint,9,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate             int64                         `protobuf:"varint,10,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	Meta                   string                        `protobuf:"bytes,11,opt,name=Meta" json:"Meta,omitempty"`
	Children               []*CompiledPostEntity         `protobuf:"bytes,12,rep,name=Children" json:"Children,omitempty"`
	PostsCount             int32                         `protobuf:"varint,13,opt,name=PostsCount" json:"PostsCount,omitempty"`
	Score                  float64                       `protobuf:"fixed64,14,opt,name=Score" json:"Score,omitempty"`
	ViewMeta_BoardName     string                        `protobuf:"bytes,15,opt,name=ViewMeta_BoardName,json=ViewMetaBoardName" json:"ViewMeta_BoardName,omitempty"`
	ViewMeta_SFWListed     bool                          `protobuf:"varint,16,opt,name=ViewMeta_SFWListed,json=ViewMetaSFWListed" json:"ViewMeta_SFWListed,omitempty"`
	ViewMeta_SearchScore   float64                       `protobuf:"fixed64,17,opt,name=ViewMeta_SearchScore,json=ViewMetaSearchScore" json:"ViewMeta_SearchScore,omitempty"`
}

func (m *CompiledThreadEntity) Reset()                    { *m = CompiledThreadEntity{} }
func (m *CompiledThreadEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledThreadEntity) ProtoMessage()               {}
func (*CompiledThreadEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CompiledThreadEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledThreadEntity) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *CompiledThreadEntity) GetSelfCreated() bool {
	if m != nil {
		return m.SelfCreated
	}
	return false
}

func (m *CompiledThreadEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CompiledThreadEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CompiledThreadEntity) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *CompiledThreadEntity) GetCompiledContentSignals() *CompiledContentSignalsEntity {
	if m != nil {
		return m.CompiledContentSignals
	}
	return nil
}

func (m *CompiledThreadEntity) GetOwner() *CompiledUserEntity {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CompiledThreadEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledThreadEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledThreadEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledThreadEntity) GetChildren() []*CompiledPostEntity {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *CompiledThreadEntity) GetPostsCount() int32 {
	if m != nil {
		return m.PostsCount
	}
	return 0
}

func (m *CompiledThreadEntity) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *CompiledThreadEntity) GetViewMeta_BoardName() string {
	if m != nil {
		return m.ViewMeta_BoardName
	}
	return ""
}

func (m *CompiledThreadEntity) GetViewMeta_SFWListed() bool {
	if m != nil {
		return m.ViewMeta_SFWListed
	}
	return false
}

func (m *CompiledThreadEntity) GetViewMeta_SearchScore() float64 {
	if m != nil {
		return m.ViewMeta_SearchScore
	}
	return 0
}

type CompiledPostEntity struct {
	Fingerprint            string                        `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Board                  string                        `protobuf:"bytes,2,opt,name=Board" json:"Board,omitempty"`
	Thread                 string                        `protobuf:"bytes,3,opt,name=Thread" json:"Thread,omitempty"`
	Parent                 string                        `protobuf:"bytes,4,opt,name=Parent" json:"Parent,omitempty"`
	SelfCreated            bool                          `protobuf:"varint,5,opt,name=SelfCreated" json:"SelfCreated,omitempty"`
	Body                   string                        `protobuf:"bytes,6,opt,name=Body" json:"Body,omitempty"`
	CompiledContentSignals *CompiledContentSignalsEntity `protobuf:"bytes,7,opt,name=CompiledContentSignals" json:"CompiledContentSignals,omitempty"`
	Owner                  *CompiledUserEntity           `protobuf:"bytes,8,opt,name=Owner" json:"Owner,omitempty"`
	Creation               int64                         `protobuf:"varint,9,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate             int64                         `protobuf:"varint,10,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	Meta                   string                        `protobuf:"bytes,11,opt,name=Meta" json:"Meta,omitempty"`
	Children               []*CompiledPostEntity         `protobuf:"bytes,12,rep,name=Children" json:"Children,omitempty"`
	ViewMeta_SFWListed     bool                          `protobuf:"varint,13,opt,name=ViewMeta_SFWListed,json=ViewMetaSFWListed" json:"ViewMeta_SFWListed,omitempty"`
	ViewMeta_SearchScore   float64                       `protobuf:"fixed64,14,opt,name=ViewMeta_SearchScore,json=ViewMetaSearchScore" json:"ViewMeta_SearchScore,omitempty"`
	ViewMeta_BoardName     string                        `protobuf:"bytes,15,opt,name=ViewMeta_BoardName,json=ViewMetaBoardName" json:"ViewMeta_BoardName,omitempty"`
	ViewMeta_ThreadName    string                        `protobuf:"bytes,16,opt,name=ViewMeta_ThreadName,json=ViewMetaThreadName" json:"ViewMeta_ThreadName,omitempty"`
}

func (m *CompiledPostEntity) Reset()                    { *m = CompiledPostEntity{} }
func (m *CompiledPostEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledPostEntity) ProtoMessage()               {}
func (*CompiledPostEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CompiledPostEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledPostEntity) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

func (m *CompiledPostEntity) GetThread() string {
	if m != nil {
		return m.Thread
	}
	return ""
}

func (m *CompiledPostEntity) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CompiledPostEntity) GetSelfCreated() bool {
	if m != nil {
		return m.SelfCreated
	}
	return false
}

func (m *CompiledPostEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CompiledPostEntity) GetCompiledContentSignals() *CompiledContentSignalsEntity {
	if m != nil {
		return m.CompiledContentSignals
	}
	return nil
}

func (m *CompiledPostEntity) GetOwner() *CompiledUserEntity {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *CompiledPostEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledPostEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledPostEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledPostEntity) GetChildren() []*CompiledPostEntity {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *CompiledPostEntity) GetViewMeta_SFWListed() bool {
	if m != nil {
		return m.ViewMeta_SFWListed
	}
	return false
}

func (m *CompiledPostEntity) GetViewMeta_SearchScore() float64 {
	if m != nil {
		return m.ViewMeta_SearchScore
	}
	return 0
}

func (m *CompiledPostEntity) GetViewMeta_BoardName() string {
	if m != nil {
		return m.ViewMeta_BoardName
	}
	return ""
}

func (m *CompiledPostEntity) GetViewMeta_ThreadName() string {
	if m != nil {
		return m.ViewMeta_ThreadName
	}
	return ""
}

type CompiledUserEntity struct {
	Fingerprint          string                     `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	NonCanonicalName     string                     `protobuf:"bytes,2,opt,name=NonCanonicalName" json:"NonCanonicalName,omitempty"`
	Creation             int64                      `protobuf:"varint,3,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate           int64                      `protobuf:"varint,4,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	LastRefreshed        int64                      `protobuf:"varint,5,opt,name=LastRefreshed" json:"LastRefreshed,omitempty"`
	CompiledUserSignals  *CompiledUserSignalsEntity `protobuf:"bytes,6,opt,name=CompiledUserSignals" json:"CompiledUserSignals,omitempty"`
	Expiry               int64                      `protobuf:"varint,7,opt,name=Expiry" json:"Expiry,omitempty"`
	Info                 string                     `protobuf:"bytes,8,opt,name=Info" json:"Info,omitempty"`
	Meta                 string                     `protobuf:"bytes,9,opt,name=Meta" json:"Meta,omitempty"`
	ViewMeta_SearchScore float64                    `protobuf:"fixed64,10,opt,name=ViewMeta_SearchScore,json=ViewMetaSearchScore" json:"ViewMeta_SearchScore,omitempty"`
}

func (m *CompiledUserEntity) Reset()                    { *m = CompiledUserEntity{} }
func (m *CompiledUserEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledUserEntity) ProtoMessage()               {}
func (*CompiledUserEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CompiledUserEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *CompiledUserEntity) GetNonCanonicalName() string {
	if m != nil {
		return m.NonCanonicalName
	}
	return ""
}

func (m *CompiledUserEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *CompiledUserEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *CompiledUserEntity) GetLastRefreshed() int64 {
	if m != nil {
		return m.LastRefreshed
	}
	return 0
}

func (m *CompiledUserEntity) GetCompiledUserSignals() *CompiledUserSignalsEntity {
	if m != nil {
		return m.CompiledUserSignals
	}
	return nil
}

func (m *CompiledUserEntity) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *CompiledUserEntity) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CompiledUserEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *CompiledUserEntity) GetViewMeta_SearchScore() float64 {
	if m != nil {
		return m.ViewMeta_SearchScore
	}
	return 0
}

type CUserUsername struct {
	SourceCUser string `protobuf:"bytes,1,opt,name=SourceCUser" json:"SourceCUser,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Canonical   bool   `protobuf:"varint,3,opt,name=Canonical" json:"Canonical,omitempty"`
}

func (m *CUserUsername) Reset()                    { *m = CUserUsername{} }
func (m *CUserUsername) String() string            { return proto.CompactTextString(m) }
func (*CUserUsername) ProtoMessage()               {}
func (*CUserUsername) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CUserUsername) GetSourceCUser() string {
	if m != nil {
		return m.SourceCUser
	}
	return ""
}

func (m *CUserUsername) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CUserUsername) GetCanonical() bool {
	if m != nil {
		return m.Canonical
	}
	return false
}

type CompiledContentSignalsEntity struct {
	TargetFingerprint string `protobuf:"bytes,1,opt,name=TargetFingerprint" json:"TargetFingerprint,omitempty"`
	// ATD
	Upvotes            int32                    `protobuf:"varint,2,opt,name=Upvotes" json:"Upvotes,omitempty"`
	Downvotes          int32                    `protobuf:"varint,3,opt,name=Downvotes" json:"Downvotes,omitempty"`
	SelfUpvoted        bool                     `protobuf:"varint,4,opt,name=SelfUpvoted" json:"SelfUpvoted,omitempty"`
	SelfDownvoted      bool                     `protobuf:"varint,5,opt,name=SelfDownvoted" json:"SelfDownvoted,omitempty"`
	SelfATDCreation    int64                    `protobuf:"varint,6,opt,name=SelfATDCreation" json:"SelfATDCreation,omitempty"`
	SelfATDLastUpdate  int64                    `protobuf:"varint,7,opt,name=SelfATDLastUpdate" json:"SelfATDLastUpdate,omitempty"`
	SelfATDFingerprint string                   `protobuf:"bytes,8,opt,name=SelfATDFingerprint" json:"SelfATDFingerprint,omitempty"`
	Reports            []*ExplainedSignalEntity `protobuf:"bytes,9,rep,name=Reports" json:"Reports,omitempty"`
	// bool SelfReported = 10;
	ModBlocks        []*ExplainedSignalEntity `protobuf:"bytes,11,rep,name=ModBlocks" json:"ModBlocks,omitempty"`
	ModApprovals     []*ExplainedSignalEntity `protobuf:"bytes,12,rep,name=ModApprovals" json:"ModApprovals,omitempty"`
	ByMod            bool                     `protobuf:"varint,13,opt,name=ByMod" json:"ByMod,omitempty"`
	ByFollowedPerson bool                     `protobuf:"varint,14,opt,name=ByFollowedPerson" json:"ByFollowedPerson,omitempty"`
	ByBlockedPerson  bool                     `protobuf:"varint,15,opt,name=ByBlockedPerson" json:"ByBlockedPerson,omitempty"`
	ByOP             bool                     `protobuf:"varint,16,opt,name=ByOP" json:"ByOP,omitempty"`
	ModBlocked       bool                     `protobuf:"varint,17,opt,name=ModBlocked" json:"ModBlocked,omitempty"`
	ModApproved      bool                     `protobuf:"varint,18,opt,name=ModApproved" json:"ModApproved,omitempty"`
	LastRefreshed    int64                    `protobuf:"varint,19,opt,name=LastRefreshed" json:"LastRefreshed,omitempty"`
	SelfModApproved  bool                     `protobuf:"varint,20,opt,name=SelfModApproved" json:"SelfModApproved,omitempty"`
	SelfModBlocked   bool                     `protobuf:"varint,21,opt,name=SelfModBlocked" json:"SelfModBlocked,omitempty"`
	SelfModIgnored   bool                     `protobuf:"varint,22,opt,name=SelfModIgnored" json:"SelfModIgnored,omitempty"`
	SelfReported     bool                     `protobuf:"varint,23,opt,name=SelfReported" json:"SelfReported,omitempty"`
}

func (m *CompiledContentSignalsEntity) Reset()                    { *m = CompiledContentSignalsEntity{} }
func (m *CompiledContentSignalsEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledContentSignalsEntity) ProtoMessage()               {}
func (*CompiledContentSignalsEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CompiledContentSignalsEntity) GetTargetFingerprint() string {
	if m != nil {
		return m.TargetFingerprint
	}
	return ""
}

func (m *CompiledContentSignalsEntity) GetUpvotes() int32 {
	if m != nil {
		return m.Upvotes
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetDownvotes() int32 {
	if m != nil {
		return m.Downvotes
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfUpvoted() bool {
	if m != nil {
		return m.SelfUpvoted
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfDownvoted() bool {
	if m != nil {
		return m.SelfDownvoted
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfATDCreation() int64 {
	if m != nil {
		return m.SelfATDCreation
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfATDLastUpdate() int64 {
	if m != nil {
		return m.SelfATDLastUpdate
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfATDFingerprint() string {
	if m != nil {
		return m.SelfATDFingerprint
	}
	return ""
}

func (m *CompiledContentSignalsEntity) GetReports() []*ExplainedSignalEntity {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *CompiledContentSignalsEntity) GetModBlocks() []*ExplainedSignalEntity {
	if m != nil {
		return m.ModBlocks
	}
	return nil
}

func (m *CompiledContentSignalsEntity) GetModApprovals() []*ExplainedSignalEntity {
	if m != nil {
		return m.ModApprovals
	}
	return nil
}

func (m *CompiledContentSignalsEntity) GetByMod() bool {
	if m != nil {
		return m.ByMod
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetByFollowedPerson() bool {
	if m != nil {
		return m.ByFollowedPerson
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetByBlockedPerson() bool {
	if m != nil {
		return m.ByBlockedPerson
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetByOP() bool {
	if m != nil {
		return m.ByOP
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetModBlocked() bool {
	if m != nil {
		return m.ModBlocked
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetModApproved() bool {
	if m != nil {
		return m.ModApproved
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetLastRefreshed() int64 {
	if m != nil {
		return m.LastRefreshed
	}
	return 0
}

func (m *CompiledContentSignalsEntity) GetSelfModApproved() bool {
	if m != nil {
		return m.SelfModApproved
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfModBlocked() bool {
	if m != nil {
		return m.SelfModBlocked
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfModIgnored() bool {
	if m != nil {
		return m.SelfModIgnored
	}
	return false
}

func (m *CompiledContentSignalsEntity) GetSelfReported() bool {
	if m != nil {
		return m.SelfReported
	}
	return false
}

type ExplainedSignalEntity struct {
	SourceFp   string `protobuf:"bytes,1,opt,name=SourceFp" json:"SourceFp,omitempty"`
	Reason     string `protobuf:"bytes,2,opt,name=Reason" json:"Reason,omitempty"`
	Creation   int64  `protobuf:"varint,3,opt,name=Creation" json:"Creation,omitempty"`
	LastUpdate int64  `protobuf:"varint,4,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
}

func (m *ExplainedSignalEntity) Reset()                    { *m = ExplainedSignalEntity{} }
func (m *ExplainedSignalEntity) String() string            { return proto.CompactTextString(m) }
func (*ExplainedSignalEntity) ProtoMessage()               {}
func (*ExplainedSignalEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExplainedSignalEntity) GetSourceFp() string {
	if m != nil {
		return m.SourceFp
	}
	return ""
}

func (m *ExplainedSignalEntity) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ExplainedSignalEntity) GetCreation() int64 {
	if m != nil {
		return m.Creation
	}
	return 0
}

func (m *ExplainedSignalEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

type CompiledUserSignalsEntity struct {
	TargetFingerprint      string `protobuf:"bytes,1,opt,name=TargetFingerprint" json:"TargetFingerprint,omitempty"`
	Domain                 string `protobuf:"bytes,2,opt,name=Domain" json:"Domain,omitempty"`
	FollowedBySelf         bool   `protobuf:"varint,3,opt,name=FollowedBySelf" json:"FollowedBySelf,omitempty"`
	BlockedBySelf          bool   `protobuf:"varint,4,opt,name=BlockedBySelf" json:"BlockedBySelf,omitempty"`
	FollowerCount          int32  `protobuf:"varint,5,opt,name=FollowerCount" json:"FollowerCount,omitempty"`
	CanonicalName          string `protobuf:"bytes,6,opt,name=CanonicalName" json:"CanonicalName,omitempty"`
	CNameSourceFingerprint string `protobuf:"bytes,7,opt,name=CNameSourceFingerprint" json:"CNameSourceFingerprint,omitempty"`
	SelfPEFingerprint      string `protobuf:"bytes,8,opt,name=SelfPEFingerprint" json:"SelfPEFingerprint,omitempty"`
	SelfPECreation         int64  `protobuf:"varint,9,opt,name=SelfPECreation" json:"SelfPECreation,omitempty"`
	SelfPELastUpdate       int64  `protobuf:"varint,10,opt,name=SelfPELastUpdate" json:"SelfPELastUpdate,omitempty"`
	MadeModBySelf          bool   `protobuf:"varint,11,opt,name=MadeModBySelf" json:"MadeModBySelf,omitempty"`
	MadeNonModBySelf       bool   `protobuf:"varint,12,opt,name=MadeNonModBySelf" json:"MadeNonModBySelf,omitempty"`
	MadeModByDefault       bool   `protobuf:"varint,13,opt,name=MadeModByDefault" json:"MadeModByDefault,omitempty"`
	MadeModByNetwork       bool   `protobuf:"varint,14,opt,name=MadeModByNetwork" json:"MadeModByNetwork,omitempty"`
	MadeNonModByNetwork    bool   `protobuf:"varint,15,opt,name=MadeNonModByNetwork" json:"MadeNonModByNetwork,omitempty"`
}

func (m *CompiledUserSignalsEntity) Reset()                    { *m = CompiledUserSignalsEntity{} }
func (m *CompiledUserSignalsEntity) String() string            { return proto.CompactTextString(m) }
func (*CompiledUserSignalsEntity) ProtoMessage()               {}
func (*CompiledUserSignalsEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CompiledUserSignalsEntity) GetTargetFingerprint() string {
	if m != nil {
		return m.TargetFingerprint
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetFollowedBySelf() bool {
	if m != nil {
		return m.FollowedBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetBlockedBySelf() bool {
	if m != nil {
		return m.BlockedBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetFollowerCount() int32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *CompiledUserSignalsEntity) GetCanonicalName() string {
	if m != nil {
		return m.CanonicalName
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetCNameSourceFingerprint() string {
	if m != nil {
		return m.CNameSourceFingerprint
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetSelfPEFingerprint() string {
	if m != nil {
		return m.SelfPEFingerprint
	}
	return ""
}

func (m *CompiledUserSignalsEntity) GetSelfPECreation() int64 {
	if m != nil {
		return m.SelfPECreation
	}
	return 0
}

func (m *CompiledUserSignalsEntity) GetSelfPELastUpdate() int64 {
	if m != nil {
		return m.SelfPELastUpdate
	}
	return 0
}

func (m *CompiledUserSignalsEntity) GetMadeModBySelf() bool {
	if m != nil {
		return m.MadeModBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeNonModBySelf() bool {
	if m != nil {
		return m.MadeNonModBySelf
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeModByDefault() bool {
	if m != nil {
		return m.MadeModByDefault
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeModByNetwork() bool {
	if m != nil {
		return m.MadeModByNetwork
	}
	return false
}

func (m *CompiledUserSignalsEntity) GetMadeNonModByNetwork() bool {
	if m != nil {
		return m.MadeNonModByNetwork
	}
	return false
}

type AmbientBoardEntity struct {
	Fingerprint          string `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	Name                 string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	LastUpdate           int64  `protobuf:"varint,3,opt,name=LastUpdate" json:"LastUpdate,omitempty"`
	LastSeen             int64  `protobuf:"varint,4,opt,name=LastSeen" json:"LastSeen,omitempty"`
	Notify               bool   `protobuf:"varint,5,opt,name=Notify" json:"Notify,omitempty"`
	UserCount            int64  `protobuf:"varint,6,opt,name=UserCount" json:"UserCount,omitempty"`
	LastNewThreadArrived int64  `protobuf:"varint,7,opt,name=LastNewThreadArrived" json:"LastNewThreadArrived,omitempty"`
}

func (m *AmbientBoardEntity) Reset()                    { *m = AmbientBoardEntity{} }
func (m *AmbientBoardEntity) String() string            { return proto.CompactTextString(m) }
func (*AmbientBoardEntity) ProtoMessage()               {}
func (*AmbientBoardEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AmbientBoardEntity) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *AmbientBoardEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AmbientBoardEntity) GetLastUpdate() int64 {
	if m != nil {
		return m.LastUpdate
	}
	return 0
}

func (m *AmbientBoardEntity) GetLastSeen() int64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *AmbientBoardEntity) GetNotify() bool {
	if m != nil {
		return m.Notify
	}
	return false
}

func (m *AmbientBoardEntity) GetUserCount() int64 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *AmbientBoardEntity) GetLastNewThreadArrived() int64 {
	if m != nil {
		return m.LastNewThreadArrived
	}
	return 0
}

// This is the status of the backend and what it is doing
type BackendAmbientStatus struct {
	// ----------  Bootstrap  ----------
	BootstrapInProgress     bool  `protobuf:"varint,18,opt,name=BootstrapInProgress" json:"BootstrapInProgress,omitempty"`
	LastBootstrapTimestamp  int64 `protobuf:"varint,19,opt,name=LastBootstrapTimestamp" json:"LastBootstrapTimestamp,omitempty"`
	TriggerBootstrapRefresh bool  `protobuf:"varint,20,opt,name=TriggerBootstrapRefresh" json:"TriggerBootstrapRefresh,omitempty"`
	// ----------  Inbounds  ----------
	LastInboundConnTimestamp int64 `protobuf:"varint,1,opt,name=LastInboundConnTimestamp" json:"LastInboundConnTimestamp,omitempty"`
	InboundsCount15          int32 `protobuf:"varint,2,opt,name=InboundsCount15" json:"InboundsCount15,omitempty"`
	// ----------  Outbounds  ----------
	LastOutboundConnTimestamp   int64 `protobuf:"varint,3,opt,name=LastOutboundConnTimestamp" json:"LastOutboundConnTimestamp,omitempty"`
	OutboundsCount15            int32 `protobuf:"varint,4,opt,name=OutboundsCount15" json:"OutboundsCount15,omitempty"`
	LastOutboundDurationSeconds int32 `protobuf:"varint,5,opt,name=LastOutboundDurationSeconds" json:"LastOutboundDurationSeconds,omitempty"`
	// ----------  Misc  ----------
	LocalNodeExternalIP   string `protobuf:"bytes,6,opt,name=LocalNodeExternalIP" json:"LocalNodeExternalIP,omitempty"`
	LocalNodeExternalPort int32  `protobuf:"varint,7,opt,name=LocalNodeExternalPort" json:"LocalNodeExternalPort,omitempty"`
	UPNPStatus            string `protobuf:"bytes,8,opt,name=UPNPStatus" json:"UPNPStatus,omitempty"`
	// ----------  DATABASE  ----------
	DatabaseStatus            string `protobuf:"bytes,9,opt,name=DatabaseStatus" json:"DatabaseStatus,omitempty"`
	DbSizeMb                  int64  `protobuf:"varint,10,opt,name=DbSizeMb" json:"DbSizeMb,omitempty"`
	MaxDbSizeMb               int64  `protobuf:"varint,11,opt,name=MaxDbSizeMb" json:"MaxDbSizeMb,omitempty"`
	LastDbInsertTimestamp     int64  `protobuf:"varint,12,opt,name=LastDbInsertTimestamp" json:"LastDbInsertTimestamp,omitempty"`
	LastInsertDurationSeconds int32  `protobuf:"varint,13,opt,name=LastInsertDurationSeconds" json:"LastInsertDurationSeconds,omitempty"`
	// ----------  CACHING  ----------
	CachingStatus                      string `protobuf:"bytes,14,opt,name=CachingStatus" json:"CachingStatus,omitempty"`
	LastCacheGenerationTimestamp       int64  `protobuf:"varint,15,opt,name=LastCacheGenerationTimestamp" json:"LastCacheGenerationTimestamp,omitempty"`
	LastCacheGenerationDurationSeconds int32  `protobuf:"varint,16,opt,name=LastCacheGenerationDurationSeconds" json:"LastCacheGenerationDurationSeconds,omitempty"`
	// ----------  CONFIG LOCATION  ----------
	BackendConfigLocation string `protobuf:"bytes,17,opt,name=BackendConfigLocation" json:"BackendConfigLocation,omitempty"`
}

func (m *BackendAmbientStatus) Reset()                    { *m = BackendAmbientStatus{} }
func (m *BackendAmbientStatus) String() string            { return proto.CompactTextString(m) }
func (*BackendAmbientStatus) ProtoMessage()               {}
func (*BackendAmbientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BackendAmbientStatus) GetBootstrapInProgress() bool {
	if m != nil {
		return m.BootstrapInProgress
	}
	return false
}

func (m *BackendAmbientStatus) GetLastBootstrapTimestamp() int64 {
	if m != nil {
		return m.LastBootstrapTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetTriggerBootstrapRefresh() bool {
	if m != nil {
		return m.TriggerBootstrapRefresh
	}
	return false
}

func (m *BackendAmbientStatus) GetLastInboundConnTimestamp() int64 {
	if m != nil {
		return m.LastInboundConnTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetInboundsCount15() int32 {
	if m != nil {
		return m.InboundsCount15
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastOutboundConnTimestamp() int64 {
	if m != nil {
		return m.LastOutboundConnTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetOutboundsCount15() int32 {
	if m != nil {
		return m.OutboundsCount15
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastOutboundDurationSeconds() int32 {
	if m != nil {
		return m.LastOutboundDurationSeconds
	}
	return 0
}

func (m *BackendAmbientStatus) GetLocalNodeExternalIP() string {
	if m != nil {
		return m.LocalNodeExternalIP
	}
	return ""
}

func (m *BackendAmbientStatus) GetLocalNodeExternalPort() int32 {
	if m != nil {
		return m.LocalNodeExternalPort
	}
	return 0
}

func (m *BackendAmbientStatus) GetUPNPStatus() string {
	if m != nil {
		return m.UPNPStatus
	}
	return ""
}

func (m *BackendAmbientStatus) GetDatabaseStatus() string {
	if m != nil {
		return m.DatabaseStatus
	}
	return ""
}

func (m *BackendAmbientStatus) GetDbSizeMb() int64 {
	if m != nil {
		return m.DbSizeMb
	}
	return 0
}

func (m *BackendAmbientStatus) GetMaxDbSizeMb() int64 {
	if m != nil {
		return m.MaxDbSizeMb
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastDbInsertTimestamp() int64 {
	if m != nil {
		return m.LastDbInsertTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastInsertDurationSeconds() int32 {
	if m != nil {
		return m.LastInsertDurationSeconds
	}
	return 0
}

func (m *BackendAmbientStatus) GetCachingStatus() string {
	if m != nil {
		return m.CachingStatus
	}
	return ""
}

func (m *BackendAmbientStatus) GetLastCacheGenerationTimestamp() int64 {
	if m != nil {
		return m.LastCacheGenerationTimestamp
	}
	return 0
}

func (m *BackendAmbientStatus) GetLastCacheGenerationDurationSeconds() int32 {
	if m != nil {
		return m.LastCacheGenerationDurationSeconds
	}
	return 0
}

func (m *BackendAmbientStatus) GetBackendConfigLocation() string {
	if m != nil {
		return m.BackendConfigLocation
	}
	return ""
}

type FrontendAmbientStatus struct {
	RefresherStatus            string `protobuf:"bytes,1,opt,name=RefresherStatus" json:"RefresherStatus,omitempty"`
	LastRefreshTimestamp       int64  `protobuf:"varint,2,opt,name=LastRefreshTimestamp" json:"LastRefreshTimestamp,omitempty"`
	LastRefreshDurationSeconds int32  `protobuf:"varint,3,opt,name=LastRefreshDurationSeconds" json:"LastRefreshDurationSeconds,omitempty"`
	FrontendConfigLocation     string `protobuf:"bytes,4,opt,name=FrontendConfigLocation" json:"FrontendConfigLocation,omitempty"`
	SFWListDisabled            bool   `protobuf:"varint,5,opt,name=SFWListDisabled" json:"SFWListDisabled,omitempty"`
	BootstrapRefreshInProgress bool   `protobuf:"varint,6,opt,name=BootstrapRefreshInProgress" json:"BootstrapRefreshInProgress,omitempty"`
	BootstrapRefreshComplete   bool   `protobuf:"varint,7,opt,name=BootstrapRefreshComplete" json:"BootstrapRefreshComplete,omitempty"`
}

func (m *FrontendAmbientStatus) Reset()                    { *m = FrontendAmbientStatus{} }
func (m *FrontendAmbientStatus) String() string            { return proto.CompactTextString(m) }
func (*FrontendAmbientStatus) ProtoMessage()               {}
func (*FrontendAmbientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FrontendAmbientStatus) GetRefresherStatus() string {
	if m != nil {
		return m.RefresherStatus
	}
	return ""
}

func (m *FrontendAmbientStatus) GetLastRefreshTimestamp() int64 {
	if m != nil {
		return m.LastRefreshTimestamp
	}
	return 0
}

func (m *FrontendAmbientStatus) GetLastRefreshDurationSeconds() int32 {
	if m != nil {
		return m.LastRefreshDurationSeconds
	}
	return 0
}

func (m *FrontendAmbientStatus) GetFrontendConfigLocation() string {
	if m != nil {
		return m.FrontendConfigLocation
	}
	return ""
}

func (m *FrontendAmbientStatus) GetSFWListDisabled() bool {
	if m != nil {
		return m.SFWListDisabled
	}
	return false
}

func (m *FrontendAmbientStatus) GetBootstrapRefreshInProgress() bool {
	if m != nil {
		return m.BootstrapRefreshInProgress
	}
	return false
}

func (m *FrontendAmbientStatus) GetBootstrapRefreshComplete() bool {
	if m != nil {
		return m.BootstrapRefreshComplete
	}
	return false
}

type CompiledNotification struct {
	Type                    NotificationType      `protobuf:"varint,1,opt,name=Type,enum=feobjects.NotificationType" json:"Type,omitempty"`
	Text                    string                `protobuf:"bytes,2,opt,name=Text" json:"Text,omitempty"`
	ResponsePosts           []string              `protobuf:"bytes,3,rep,name=ResponsePosts" json:"ResponsePosts,omitempty"`
	ResponsePostsUsers      []*CUserUsername      `protobuf:"bytes,4,rep,name=ResponsePostsUsers" json:"ResponsePostsUsers,omitempty"`
	ParentThread            *CompiledThreadEntity `protobuf:"bytes,5,opt,name=ParentThread" json:"ParentThread,omitempty"`
	ParentPost              *CompiledPostEntity   `protobuf:"bytes,6,opt,name=ParentPost" json:"ParentPost,omitempty"`
	CreationTimestamp       int64                 `protobuf:"varint,7,opt,name=CreationTimestamp" json:"CreationTimestamp,omitempty"`
	NewestResponseTimestamp int64                 `protobuf:"varint,8,opt,name=NewestResponseTimestamp" json:"NewestResponseTimestamp,omitempty"`
	Read                    bool                  `protobuf:"varint,9,opt,name=Read" json:"Read,omitempty"`
}

func (m *CompiledNotification) Reset()                    { *m = CompiledNotification{} }
func (m *CompiledNotification) String() string            { return proto.CompactTextString(m) }
func (*CompiledNotification) ProtoMessage()               {}
func (*CompiledNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CompiledNotification) GetType() NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationType_UNKNOWN_NOTIFICATION_TYPE
}

func (m *CompiledNotification) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CompiledNotification) GetResponsePosts() []string {
	if m != nil {
		return m.ResponsePosts
	}
	return nil
}

func (m *CompiledNotification) GetResponsePostsUsers() []*CUserUsername {
	if m != nil {
		return m.ResponsePostsUsers
	}
	return nil
}

func (m *CompiledNotification) GetParentThread() *CompiledThreadEntity {
	if m != nil {
		return m.ParentThread
	}
	return nil
}

func (m *CompiledNotification) GetParentPost() *CompiledPostEntity {
	if m != nil {
		return m.ParentPost
	}
	return nil
}

func (m *CompiledNotification) GetCreationTimestamp() int64 {
	if m != nil {
		return m.CreationTimestamp
	}
	return 0
}

func (m *CompiledNotification) GetNewestResponseTimestamp() int64 {
	if m != nil {
		return m.NewestResponseTimestamp
	}
	return 0
}

func (m *CompiledNotification) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

type ReportsTabEntry struct {
	Fingerprint   string                `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	BoardPayload  *CompiledBoardEntity  `protobuf:"bytes,2,opt,name=BoardPayload" json:"BoardPayload,omitempty"`
	ThreadPayload *CompiledThreadEntity `protobuf:"bytes,3,opt,name=ThreadPayload" json:"ThreadPayload,omitempty"`
	PostPayload   *CompiledPostEntity   `protobuf:"bytes,4,opt,name=PostPayload" json:"PostPayload,omitempty"`
	Timestamp     int64                 `protobuf:"varint,5,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *ReportsTabEntry) Reset()                    { *m = ReportsTabEntry{} }
func (m *ReportsTabEntry) String() string            { return proto.CompactTextString(m) }
func (*ReportsTabEntry) ProtoMessage()               {}
func (*ReportsTabEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ReportsTabEntry) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *ReportsTabEntry) GetBoardPayload() *CompiledBoardEntity {
	if m != nil {
		return m.BoardPayload
	}
	return nil
}

func (m *ReportsTabEntry) GetThreadPayload() *CompiledThreadEntity {
	if m != nil {
		return m.ThreadPayload
	}
	return nil
}

func (m *ReportsTabEntry) GetPostPayload() *CompiledPostEntity {
	if m != nil {
		return m.PostPayload
	}
	return nil
}

func (m *ReportsTabEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ModActionsTabEntry struct {
	Fingerprint   string                `protobuf:"bytes,1,opt,name=Fingerprint" json:"Fingerprint,omitempty"`
	BoardPayload  *CompiledBoardEntity  `protobuf:"bytes,2,opt,name=BoardPayload" json:"BoardPayload,omitempty"`
	ThreadPayload *CompiledThreadEntity `protobuf:"bytes,3,opt,name=ThreadPayload" json:"ThreadPayload,omitempty"`
	PostPayload   *CompiledPostEntity   `protobuf:"bytes,4,opt,name=PostPayload" json:"PostPayload,omitempty"`
	Timestamp     int64                 `protobuf:"varint,5,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *ModActionsTabEntry) Reset()                    { *m = ModActionsTabEntry{} }
func (m *ModActionsTabEntry) String() string            { return proto.CompactTextString(m) }
func (*ModActionsTabEntry) ProtoMessage()               {}
func (*ModActionsTabEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ModActionsTabEntry) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *ModActionsTabEntry) GetBoardPayload() *CompiledBoardEntity {
	if m != nil {
		return m.BoardPayload
	}
	return nil
}

func (m *ModActionsTabEntry) GetThreadPayload() *CompiledThreadEntity {
	if m != nil {
		return m.ThreadPayload
	}
	return nil
}

func (m *ModActionsTabEntry) GetPostPayload() *CompiledPostEntity {
	if m != nil {
		return m.PostPayload
	}
	return nil
}

func (m *ModActionsTabEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*CompiledBoardEntity)(nil), "feobjects.CompiledBoardEntity")
	proto.RegisterType((*CompiledThreadEntity)(nil), "feobjects.CompiledThreadEntity")
	proto.RegisterType((*CompiledPostEntity)(nil), "feobjects.CompiledPostEntity")
	proto.RegisterType((*CompiledUserEntity)(nil), "feobjects.CompiledUserEntity")
	proto.RegisterType((*CUserUsername)(nil), "feobjects.CUserUsername")
	proto.RegisterType((*CompiledContentSignalsEntity)(nil), "feobjects.CompiledContentSignalsEntity")
	proto.RegisterType((*ExplainedSignalEntity)(nil), "feobjects.ExplainedSignalEntity")
	proto.RegisterType((*CompiledUserSignalsEntity)(nil), "feobjects.CompiledUserSignalsEntity")
	proto.RegisterType((*AmbientBoardEntity)(nil), "feobjects.AmbientBoardEntity")
	proto.RegisterType((*BackendAmbientStatus)(nil), "feobjects.BackendAmbientStatus")
	proto.RegisterType((*FrontendAmbientStatus)(nil), "feobjects.FrontendAmbientStatus")
	proto.RegisterType((*CompiledNotification)(nil), "feobjects.CompiledNotification")
	proto.RegisterType((*ReportsTabEntry)(nil), "feobjects.ReportsTabEntry")
	proto.RegisterType((*ModActionsTabEntry)(nil), "feobjects.ModActionsTabEntry")
	proto.RegisterEnum("feobjects.NotificationType", NotificationType_name, NotificationType_value)
}

func init() { proto.RegisterFile("feobjects/feobjects.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2076 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x5f, 0x73, 0x2b, 0x37,
	0x15, 0xc7, 0xb1, 0x9d, 0xc4, 0x8a, 0x93, 0x38, 0x4a, 0x6e, 0xba, 0xb7, 0xbd, 0x2d, 0x1e, 0x53,
	0xc0, 0xd3, 0xa1, 0xf7, 0xd2, 0x14, 0x18, 0xe8, 0x40, 0x21, 0xfe, 0x13, 0xea, 0x21, 0x71, 0x3c,
	0x6b, 0xa7, 0x9d, 0xcb, 0x4b, 0x66, 0xed, 0x55, 0x9c, 0x25, 0x8e, 0xe4, 0xd1, 0x6e, 0x6e, 0x62,
	0xbe, 0x00, 0x8f, 0x0c, 0x03, 0xbc, 0x01, 0xc3, 0xf7, 0xe1, 0xcb, 0xf0, 0xc6, 0x2b, 0x73, 0x8e,
	0xb4, 0xbb, 0xda, 0xf5, 0xae, 0x6f, 0x02, 0x7d, 0xec, 0x83, 0x67, 0xa4, 0xdf, 0x39, 0xd2, 0x1e,
	0x9d, 0xf3, 0xd3, 0xd1, 0x91, 0x4c, 0x9e, 0x5f, 0x31, 0x31, 0xfe, 0x1d, 0x9b, 0x04, 0xfe, 0xab,
	0xa8, 0xf5, 0x72, 0x2e, 0x45, 0x20, 0x68, 0x25, 0x02, 0x1a, 0xff, 0x29, 0x93, 0xfd, 0xb6, 0xb8,
	0x9d, 0x7b, 0x33, 0xe6, 0xb6, 0x84, 0x23, 0xdd, 0x2e, 0x0f, 0xbc, 0x60, 0x41, 0xeb, 0x64, 0xeb,
	0xc4, 0xe3, 0x53, 0x26, 0xe7, 0xd2, 0xe3, 0x81, 0x55, 0xa8, 0x17, 0x9a, 0x15, 0xdb, 0x84, 0x40,
	0x63, 0xc8, 0x66, 0x57, 0x6d, 0xc9, 0x9c, 0x80, 0xb9, 0xd6, 0x5a, 0xbd, 0xd0, 0xdc, 0xb4, 0x4d,
	0x88, 0x52, 0x52, 0xea, 0x3b, 0xb7, 0xcc, 0x2a, 0xe2, 0x60, 0x6c, 0xc3, 0xa8, 0x0e, 0xf3, 0x27,
	0xd2, 0x9b, 0x07, 0x9e, 0xe0, 0x56, 0x49, 0xcd, 0x6b, 0x40, 0xf4, 0x92, 0x1c, 0x86, 0x06, 0xb5,
	0x05, 0x0f, 0x18, 0x0f, 0x86, 0xde, 0x94, 0x3b, 0x33, 0xdf, 0x2a, 0xd7, 0x0b, 0xcd, 0xad, 0xa3,
	0xef, 0xbf, 0x8c, 0x97, 0x93, 0xad, 0xa8, 0x96, 0x60, 0xe7, 0x4c, 0x43, 0x3f, 0x25, 0xe5, 0xf3,
	0x7b, 0xce, 0xa4, 0xb5, 0x8e, 0xf3, 0xbd, 0x9f, 0x31, 0xdf, 0x85, 0xcf, 0xa4, 0x9e, 0x45, 0xe9,
	0x82, 0xdd, 0xe8, 0x1e, 0xec, 0xf9, 0xd6, 0x46, 0xbd, 0x08, 0x76, 0x1b, 0x10, 0x7d, 0x97, 0x6c,
	0xe2, 0xc2, 0x61, 0x59, 0x9b, 0xf5, 0x42, 0xb3, 0x68, 0x47, 0x7d, 0xfa, 0x01, 0x21, 0xa7, 0x8e,
	0x1f, 0x5c, 0xcc, 0x5d, 0x27, 0x60, 0x56, 0x05, 0xa5, 0x06, 0x02, 0x9e, 0x3a, 0x63, 0x81, 0x63,
	0x11, 0xe5, 0x29, 0x68, 0xd3, 0x36, 0xa9, 0xb6, 0xaf, 0xbd, 0x99, 0x3b, 0xba, 0x96, 0xcc, 0x71,
	0x7d, 0x6b, 0xab, 0x5e, 0x6c, 0x6e, 0x1d, 0x7d, 0x3b, 0xc3, 0x5a, 0xa5, 0xa1, 0xed, 0x4d, 0x0c,
	0xa2, 0x0d, 0x52, 0xd5, 0xcd, 0xb6, 0xb8, 0xe3, 0x81, 0x55, 0xad, 0x17, 0x9a, 0x65, 0x3b, 0x81,
	0xd1, 0x17, 0xa4, 0x02, 0xeb, 0x55, 0x0a, 0xdb, 0xa8, 0x10, 0x03, 0x60, 0xfa, 0xf0, 0x6e, 0x0c,
	0xe1, 0x19, 0x33, 0xd7, 0xda, 0xc1, 0x28, 0x1b, 0x08, 0x3d, 0x24, 0xeb, 0x7d, 0x11, 0x78, 0x57,
	0x0b, 0x6b, 0x17, 0x65, 0xba, 0x07, 0xee, 0x80, 0x05, 0x0e, 0x19, 0xe3, 0x56, 0x4d, 0xb9, 0x23,
	0xec, 0xc3, 0x17, 0x87, 0x27, 0x5f, 0x9d, 0x7a, 0x3e, 0x10, 0x67, 0x0f, 0x87, 0xc5, 0x00, 0xfd,
	0x84, 0x1c, 0x7c, 0xe9, 0xb1, 0x7b, 0x70, 0xc2, 0xe5, 0x90, 0x39, 0x72, 0x72, 0x3d, 0x9c, 0x08,
	0xc9, 0x2c, 0x5a, 0x2f, 0x34, 0x0b, 0xf6, 0x7e, 0x28, 0x33, 0x44, 0xf4, 0x88, 0x1c, 0xc0, 0xe4,
	0x7d, 0x76, 0xaf, 0x56, 0x76, 0x2c, 0xa5, 0xf7, 0x86, 0xb9, 0xd6, 0x3e, 0x7e, 0x38, 0x53, 0xd6,
	0xf8, 0x4b, 0x99, 0x1c, 0x64, 0x79, 0xf0, 0x11, 0xd4, 0x3f, 0x20, 0x65, 0x8c, 0x3c, 0x92, 0xbe,
	0x62, 0xab, 0x4e, 0x7a, 0x43, 0x14, 0xf3, 0x37, 0x44, 0xc9, 0xd8, 0x10, 0x94, 0x94, 0x5a, 0xc2,
	0x5d, 0x20, 0xb9, 0x2b, 0x36, 0xb6, 0x01, 0x3b, 0xf5, 0xf8, 0x0d, 0x12, 0xb4, 0x62, 0x63, 0x7b,
	0xc5, 0xb6, 0xd8, 0xf8, 0x9a, 0xb7, 0xc5, 0xe6, 0x13, 0xb6, 0x85, 0x49, 0xfa, 0xca, 0x4a, 0xd2,
	0x93, 0x5c, 0xd2, 0x6f, 0x19, 0xa4, 0xff, 0x19, 0xd9, 0x44, 0xfe, 0x4a, 0xc6, 0xad, 0x2a, 0x12,
	0x3e, 0xcb, 0x8e, 0x81, 0xf0, 0x03, 0x6d, 0x47, 0xa4, 0x0e, 0x9f, 0x03, 0xdc, 0x37, 0x79, 0x6c,
	0x20, 0x10, 0x34, 0xc5, 0xa3, 0x1d, 0xe4, 0x91, 0xea, 0xd0, 0x8f, 0x09, 0x8d, 0xc8, 0x86, 0x61,
	0xc4, 0x00, 0xed, 0xa2, 0x49, 0x7b, 0xa1, 0x24, 0x12, 0x24, 0xd4, 0x63, 0x0a, 0xd7, 0x30, 0xd4,
	0x91, 0xfa, 0xdb, 0xa9, 0xbc, 0x97, 0x4b, 0xe5, 0xc6, 0x5f, 0xcb, 0x84, 0x2e, 0xaf, 0xf3, 0x7f,
	0x26, 0xe5, 0x21, 0x59, 0x57, 0xe4, 0xd6, 0x59, 0x58, 0xf7, 0x00, 0x1f, 0x38, 0x92, 0xf1, 0x40,
	0x93, 0x51, 0xf7, 0xd2, 0x24, 0x2e, 0x67, 0x92, 0x18, 0x09, 0xbb, 0x6e, 0x10, 0xf6, 0x1b, 0x72,
	0xbe, 0x85, 0x9c, 0xd9, 0xbc, 0xd9, 0x7e, 0x2a, 0x6f, 0x76, 0xf2, 0x53, 0xe0, 0x13, 0x89, 0xfc,
	0x8a, 0x44, 0xb3, 0x5c, 0x2a, 0x4a, 0xa0, 0x7e, 0x0d, 0xf5, 0xa3, 0x99, 0x62, 0x49, 0xe3, 0x8f,
	0xc5, 0x98, 0x97, 0xb1, 0xab, 0x1f, 0xc1, 0xcb, 0x8f, 0x48, 0xad, 0x2f, 0x78, 0xdb, 0xe1, 0x82,
	0x7b, 0x13, 0x67, 0x86, 0x9f, 0x51, 0x14, 0x5d, 0xc2, 0x13, 0x11, 0x2b, 0xae, 0x8c, 0x58, 0x69,
	0x29, 0x62, 0x1f, 0x92, 0x6d, 0xe8, 0xd9, 0xec, 0x4a, 0x32, 0xff, 0x5a, 0x73, 0xb7, 0x68, 0x27,
	0x41, 0xfa, 0x65, 0x5c, 0xee, 0xc0, 0x2a, 0x42, 0x9a, 0xaa, 0x52, 0xe0, 0xc3, 0x1c, 0x5a, 0x25,
	0x39, 0x9a, 0x35, 0x01, 0xec, 0xa7, 0xee, 0xc3, 0xdc, 0x93, 0x0b, 0x64, 0x7c, 0xd1, 0xd6, 0x3d,
	0xe0, 0x51, 0x8f, 0x5f, 0x09, 0xe4, 0x6d, 0xc5, 0xc6, 0x76, 0xc4, 0xad, 0x8a, 0xc1, 0xad, 0xbc,
	0x88, 0x93, 0xfc, 0x4c, 0x71, 0x43, 0xb6, 0xdb, 0x60, 0x02, 0xfc, 0xb8, 0xae, 0xad, 0x86, 0xe2,
	0x4e, 0x4e, 0x18, 0xc2, 0x61, 0x2c, 0x0c, 0x08, 0xfc, 0x1b, 0x6a, 0xeb, 0x18, 0x44, 0x7d, 0x38,
	0x94, 0xa3, 0x60, 0xe8, 0xc3, 0x2b, 0x06, 0x1a, 0x7f, 0xdb, 0x20, 0x2f, 0x56, 0xed, 0x5c, 0xfa,
	0x03, 0xb2, 0x37, 0x72, 0xe4, 0x94, 0x05, 0xcb, 0x74, 0x58, 0x16, 0x50, 0x8b, 0x6c, 0x5c, 0xcc,
	0xdf, 0x88, 0x80, 0xf9, 0x68, 0x47, 0xd9, 0x0e, 0xbb, 0x60, 0x46, 0x47, 0xdc, 0x73, 0x25, 0x2b,
	0xaa, 0x6a, 0x24, 0x02, 0xc2, 0xf4, 0xa4, 0x94, 0x5d, 0x64, 0x81, 0x4e, 0x4f, 0x1a, 0x02, 0x1a,
	0x40, 0x37, 0x1c, 0x12, 0xa6, 0xb0, 0x24, 0x48, 0x9b, 0x64, 0x17, 0x80, 0xe3, 0x51, 0x27, 0xe2,
	0xdb, 0x3a, 0xc6, 0x2d, 0x0d, 0xc3, 0xba, 0x34, 0x64, 0xb0, 0x4f, 0xc5, 0x78, 0x59, 0x40, 0x5f,
	0x12, 0xaa, 0x41, 0xd3, 0x0d, 0x2a, 0xf8, 0x19, 0x12, 0xfa, 0x19, 0xd9, 0xb0, 0xd9, 0x5c, 0xc8,
	0xc0, 0xb7, 0x2a, 0x98, 0x51, 0xea, 0x06, 0x05, 0xbb, 0x0f, 0xf3, 0x99, 0xe3, 0x71, 0xe6, 0x2a,
	0x4f, 0x6b, 0xfa, 0x85, 0x03, 0xe8, 0xe7, 0xa4, 0x72, 0x26, 0xdc, 0xd6, 0x4c, 0x4c, 0x6e, 0xc2,
	0xea, 0xf0, 0xed, 0xa3, 0xe3, 0x21, 0xb4, 0x43, 0xaa, 0x67, 0xc2, 0x3d, 0x9e, 0xcf, 0xa5, 0x78,
	0x03, 0x7b, 0xa0, 0xfa, 0xc8, 0x29, 0x12, 0xa3, 0xf0, 0xd8, 0x59, 0x9c, 0x89, 0x30, 0x99, 0xa9,
	0x0e, 0x6c, 0xfa, 0xd6, 0xe2, 0x44, 0xcc, 0x66, 0xe2, 0x9e, 0xb9, 0x03, 0x26, 0x7d, 0xc1, 0x75,
	0xed, 0xb8, 0x84, 0x43, 0x2c, 0x5a, 0x0b, 0xb4, 0x29, 0x52, 0x55, 0xa5, 0x64, 0x1a, 0xc6, 0xa3,
	0x67, 0x71, 0x3e, 0xd0, 0xe7, 0x2d, 0xb6, 0x21, 0x2d, 0x84, 0x4b, 0x8a, 0x8a, 0x49, 0x03, 0x01,
	0xc6, 0x44, 0xf6, 0x32, 0x17, 0x8b, 0xc8, 0x4d, 0xdb, 0x84, 0x96, 0x13, 0xc7, 0x7e, 0x56, 0xe2,
	0xd0, 0x8c, 0x31, 0xe7, 0x3a, 0x50, 0x56, 0xa6, 0x60, 0xfa, 0x3d, 0xb2, 0xa3, 0xa1, 0xd0, 0xaa,
	0x67, 0xa8, 0x98, 0x42, 0x0d, 0xbd, 0xde, 0x94, 0x0b, 0xc9, 0x5c, 0xeb, 0x30, 0xa1, 0xa7, 0x51,
	0xa8, 0xe1, 0x01, 0x51, 0x61, 0x67, 0xae, 0xf5, 0x0e, 0x6a, 0x25, 0xb0, 0xc6, 0x1f, 0x0a, 0xe4,
	0x59, 0x66, 0xb4, 0x60, 0xcb, 0xab, 0x0c, 0x70, 0x32, 0xd7, 0xdb, 0x31, 0xea, 0x43, 0xd2, 0xb2,
	0x99, 0x03, 0x0e, 0x57, 0xc9, 0x40, 0xf7, 0xfe, 0x9f, 0x34, 0xdc, 0xf8, 0x53, 0x99, 0x3c, 0xcf,
	0xcd, 0x9d, 0x4f, 0xcc, 0x12, 0x87, 0x64, 0xbd, 0x23, 0x6e, 0x1d, 0x2f, 0xb2, 0x4f, 0xf5, 0xc0,
	0x73, 0x21, 0x87, 0x5a, 0x0b, 0xf0, 0x83, 0xce, 0x57, 0x29, 0x14, 0x22, 0xab, 0x9d, 0xad, 0xd5,
	0x54, 0xbe, 0x48, 0x82, 0xa0, 0xa5, 0xc7, 0xe9, 0x3b, 0x50, 0x19, 0xb3, 0x4e, 0x12, 0x04, 0xad,
	0xe4, 0x19, 0xa6, 0xea, 0x9f, 0x24, 0x48, 0x7f, 0x42, 0x0e, 0xdb, 0xd0, 0xd0, 0x2e, 0x36, 0x16,
	0xb9, 0x81, 0xea, 0x39, 0xd2, 0x30, 0xcb, 0x0c, 0xba, 0xcb, 0x69, 0x63, 0x59, 0x10, 0x32, 0x67,
	0xd0, 0x4d, 0x95, 0x37, 0x29, 0x14, 0x76, 0xa1, 0x42, 0x96, 0x4a, 0x9d, 0x25, 0x1c, 0xd6, 0x77,
	0xe6, 0xb8, 0x0c, 0xf8, 0xa9, 0x7c, 0xb5, 0xa5, 0x7c, 0x95, 0x00, 0x61, 0x46, 0x00, 0xfa, 0x82,
	0xc7, 0x8a, 0x55, 0xb5, 0xaf, 0xd3, 0x78, 0xa8, 0x8b, 0x40, 0x87, 0x5d, 0x39, 0x77, 0xb3, 0x40,
	0x27, 0x89, 0x25, 0x3c, 0xa1, 0xdb, 0x67, 0xc1, 0xbd, 0x90, 0x37, 0x61, 0xbe, 0x48, 0xe3, 0xf4,
	0x87, 0x64, 0xdf, 0xfc, 0x56, 0xa8, 0xae, 0x72, 0x46, 0x96, 0xa8, 0xf1, 0xef, 0x02, 0xa1, 0xc7,
	0xb7, 0x63, 0x8f, 0xf1, 0xe0, 0x69, 0x6f, 0x1c, 0xe1, 0x85, 0x6d, 0xcd, 0xb8, 0xb0, 0x25, 0x37,
	0x40, 0x71, 0xa9, 0x0e, 0x31, 0x2f, 0xbe, 0xa5, 0xd4, 0xc5, 0x37, 0xbe, 0x2c, 0x97, 0x13, 0x97,
	0xe5, 0xc4, 0x15, 0x5c, 0x1d, 0x44, 0xc6, 0x15, 0x3c, 0xef, 0x76, 0xbb, 0xb1, 0xe2, 0x76, 0xfb,
	0x8f, 0x4d, 0x72, 0xd0, 0x72, 0x26, 0x37, 0x8c, 0xbb, 0x7a, 0xe5, 0xc3, 0xc0, 0x09, 0xee, 0x7c,
	0xf0, 0x5e, 0x4b, 0x88, 0xc0, 0x0f, 0xa4, 0x33, 0xef, 0xf1, 0x81, 0x14, 0x53, 0xc9, 0x7c, 0x5f,
	0xe7, 0xc5, 0x2c, 0x11, 0x70, 0x1a, 0x3e, 0x11, 0x89, 0x46, 0xde, 0x2d, 0xf3, 0x03, 0xe7, 0x76,
	0xae, 0x13, 0x65, 0x8e, 0x94, 0xfe, 0x94, 0xbc, 0x33, 0x92, 0xde, 0x74, 0xca, 0x64, 0x24, 0xd4,
	0xe9, 0x54, 0x67, 0xce, 0x3c, 0x31, 0xfd, 0x8c, 0x58, 0x30, 0x67, 0x8f, 0x8f, 0xc5, 0x1d, 0x87,
	0x72, 0x83, 0xc7, 0xdf, 0x2c, 0xe0, 0x37, 0x73, 0xe5, 0x90, 0xa7, 0x35, 0xae, 0xee, 0x7d, 0x9f,
	0xfc, 0x58, 0x57, 0x18, 0x69, 0x98, 0xfe, 0x9c, 0x3c, 0x87, 0x59, 0xce, 0xef, 0x82, 0x8c, 0xcf,
	0xa8, 0xb8, 0xe6, 0x2b, 0x00, 0x63, 0x43, 0x41, 0xf4, 0xa1, 0x12, 0x7e, 0x68, 0x09, 0xa7, 0xbf,
	0x22, 0xef, 0x99, 0x13, 0x75, 0xee, 0x24, 0xee, 0xcf, 0x21, 0x9b, 0x08, 0xee, 0xfa, 0x3a, 0xdf,
	0xac, 0x52, 0x81, 0xa8, 0x9d, 0x0a, 0x48, 0x32, 0xc2, 0x65, 0xdd, 0x87, 0x00, 0x4a, 0xb6, 0x59,
	0x6f, 0xa0, 0x73, 0x50, 0x96, 0x88, 0xfe, 0x88, 0x3c, 0x5b, 0x82, 0x07, 0x42, 0xaa, 0x44, 0x54,
	0xb6, 0xb3, 0x85, 0x40, 0xee, 0x8b, 0x41, 0x7f, 0xa0, 0xb8, 0xa2, 0x13, 0x90, 0x81, 0x40, 0xe6,
	0xe9, 0x38, 0x81, 0x33, 0x76, 0x7c, 0xa6, 0x75, 0x54, 0x11, 0x9b, 0x42, 0x61, 0x13, 0x74, 0xc6,
	0x43, 0xef, 0xf7, 0xec, 0x6c, 0xac, 0x33, 0x4e, 0xd4, 0xc7, 0x13, 0xd9, 0x79, 0x88, 0xc4, 0x5b,
	0x28, 0x36, 0x21, 0xb4, 0xdd, 0xf1, 0x83, 0xce, 0xb8, 0xc7, 0x7d, 0x26, 0x83, 0x38, 0x2a, 0x55,
	0xd4, 0xcd, 0x16, 0x86, 0xf1, 0x54, 0x70, 0xda, 0xc7, 0xea, 0x3d, 0x20, 0x5f, 0x41, 0xe5, 0xf7,
	0xc9, 0xb5, 0xc7, 0xa7, 0x7a, 0x61, 0x3b, 0x61, 0x7e, 0x37, 0x40, 0xda, 0x22, 0x2f, 0x60, 0x0a,
	0x00, 0xd9, 0xaf, 0x19, 0x67, 0x6a, 0x8e, 0xd8, 0xc0, 0x5d, 0x34, 0x70, 0xa5, 0x0e, 0xed, 0x93,
	0x46, 0x86, 0x3c, 0x6d, 0x70, 0x0d, 0x0d, 0x7e, 0x84, 0x26, 0x78, 0x4b, 0xef, 0xf4, 0xb6, 0xe0,
	0x57, 0xde, 0x14, 0x22, 0x8b, 0x87, 0xc2, 0x1e, 0xae, 0x20, 0x5b, 0xd8, 0xf8, 0x73, 0x91, 0x3c,
	0x3b, 0x91, 0x58, 0xc9, 0xa7, 0x32, 0x44, 0x93, 0xec, 0x86, 0x65, 0x8f, 0xd4, 0xbe, 0x50, 0xa9,
	0x31, 0x0d, 0x87, 0x89, 0x49, 0xc3, 0xb1, 0x17, 0xd6, 0xe2, 0xc4, 0x94, 0x96, 0xd1, 0xcf, 0xc9,
	0xbb, 0x06, 0x9e, 0x5e, 0xb5, 0x2a, 0xf8, 0x57, 0x68, 0x40, 0x36, 0x0a, 0xcd, 0x4e, 0x2d, 0x57,
	0x3d, 0x64, 0xe4, 0x48, 0xb1, 0x7e, 0x53, 0xf7, 0xeb, 0x8e, 0xe7, 0x3b, 0xe3, 0x59, 0x74, 0x33,
	0x48, 0xc3, 0x60, 0x61, 0x3a, 0x23, 0x19, 0x89, 0x72, 0x1d, 0x07, 0xad, 0xd0, 0x80, 0xec, 0x95,
	0x96, 0x42, 0x41, 0x34, 0x63, 0xfa, 0xe2, 0xb0, 0x69, 0xe7, 0xca, 0x1b, 0xff, 0x2a, 0xc6, 0x8f,
	0x92, 0x78, 0x36, 0x78, 0xda, 0xfc, 0x57, 0xa4, 0x34, 0x5a, 0xcc, 0x19, 0x46, 0x62, 0xe7, 0xe8,
	0x3d, 0xa3, 0x48, 0x37, 0xd5, 0x40, 0xc5, 0x46, 0x45, 0x38, 0xba, 0x46, 0xec, 0x21, 0x08, 0x8f,
	0x2e, 0x68, 0x03, 0xc7, 0x6d, 0xe6, 0xcf, 0x05, 0xf7, 0x19, 0x3e, 0x8c, 0x59, 0x45, 0x7c, 0xc6,
	0x4e, 0x82, 0xf4, 0x0b, 0x42, 0x13, 0x00, 0x1c, 0x44, 0xbe, 0x55, 0xc2, 0xdb, 0x81, 0x65, 0xde,
	0x90, 0xcd, 0xcb, 0xa7, 0x9d, 0x31, 0x86, 0xb6, 0x49, 0x55, 0x3d, 0x2b, 0xe9, 0x27, 0x28, 0xf5,
	0x80, 0xff, 0xf6, 0x27, 0x6c, 0x73, 0x10, 0xfd, 0x05, 0x21, 0xaa, 0x0f, 0x13, 0xaf, 0x78, 0xb3,
	0x37, 0xde, 0x5d, 0x8c, 0x01, 0x50, 0x59, 0x85, 0xf5, 0x50, 0x4c, 0x50, 0x7d, 0x7f, 0x5b, 0x12,
	0xc0, 0x99, 0xd5, 0x67, 0xf7, 0x0c, 0xd8, 0xa7, 0x56, 0x13, 0x8f, 0x51, 0x6f, 0xfa, 0x79, 0x62,
	0xf0, 0xb7, 0x0d, 0x6b, 0xac, 0xa8, 0xbb, 0x09, 0xb4, 0x1b, 0x7f, 0x5f, 0x83, 0xad, 0x84, 0xb7,
	0xb5, 0x91, 0x33, 0xee, 0xf2, 0x40, 0x3e, 0xa6, 0xe8, 0x68, 0x91, 0x2a, 0x56, 0x29, 0x03, 0x67,
	0x31, 0x13, 0x8e, 0x7a, 0xcf, 0xdb, 0x3a, 0xfa, 0x20, 0x63, 0xc9, 0x46, 0x31, 0x63, 0x27, 0xc6,
	0xd0, 0x2e, 0xd9, 0x56, 0xee, 0x0b, 0x27, 0x29, 0x3e, 0xce, 0xf5, 0xc9, 0x51, 0xf4, 0x97, 0x64,
	0x0b, 0x9c, 0x18, 0x4e, 0x52, 0x7a, 0x8c, 0xf3, 0xcd, 0x11, 0x50, 0xd8, 0xc4, 0x1e, 0x54, 0x0f,
	0x32, 0x31, 0xd0, 0xf8, 0xe7, 0x1a, 0xa1, 0x70, 0x73, 0x9a, 0x40, 0x10, 0xbe, 0x71, 0x51, 0x86,
	0x8b, 0x3e, 0x7a, 0x4d, 0x6a, 0xe9, 0x0d, 0x4e, 0xdf, 0x27, 0xcf, 0x2f, 0xfa, 0xbf, 0xe9, 0x9f,
	0x7f, 0xd5, 0xbf, 0xec, 0x9f, 0x8f, 0x7a, 0x27, 0xbd, 0xf6, 0xf1, 0xa8, 0x77, 0xde, 0xbf, 0x1c,
	0xbd, 0x1e, 0x74, 0x6b, 0xdf, 0xa2, 0xfb, 0x64, 0xd7, 0xee, 0x0e, 0x4e, 0x5f, 0x5f, 0x8e, 0xce,
	0x2f, 0x47, 0x5f, 0xd8, 0xdd, 0xe3, 0x4e, 0xad, 0x40, 0xf7, 0xc8, 0x76, 0x04, 0x0e, 0xce, 0x87,
	0xa3, 0xda, 0x5a, 0xeb, 0xbb, 0xbf, 0xfd, 0x8e, 0xc3, 0x82, 0x6b, 0x26, 0x3f, 0x9e, 0x08, 0xc9,
	0x5e, 0xa9, 0xf6, 0x2b, 0xfc, 0x87, 0xd0, 0xf8, 0xcb, 0x70, 0xbc, 0x8e, 0xc8, 0xa7, 0xff, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0x92, 0x2a, 0xc2, 0x50, 0x1c, 0x00, 0x00,
}
